{{- if .Values.client.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "redis-app.fullname" . }}-client
  labels:
    {{- include "redis-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: client
spec:
  replicas: {{ .Values.client.replicaCount }}
  selector:
    matchLabels:
      {{- include "redis-app.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: client
  template:
    metadata:
      labels:
        {{- include "redis-app.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: client
    spec:
      {{- if .Values.client.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.client.imagePullSecrets | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "redis-app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: client
        image: "{{ .Values.client.image.repository }}:{{ .Values.client.image.tag }}"
        imagePullPolicy: {{ .Values.client.image.pullPolicy }}
        env:
        - name: REDIS_HOST
          value: {{ include "redis-app.fullname" . }}
        - name: REDIS_PORT
          value: "{{ .Values.server.service.port }}"
        - name: INTERVAL_SECONDS
          value: "{{ .Values.client.intervalSeconds }}"
        command:
          - "/bin/sh"
          - "-c"
          - |
            while true; do
              echo "$(date) - Testing Redis connection and operations..."
              redis-cli -h ${REDIS_HOST} -p ${REDIS_PORT} ping
              redis-cli -h ${REDIS_HOST} -p ${REDIS_PORT} set testkey "Hello from client pod at $(date)"
              redis-cli -h ${REDIS_HOST} -p ${REDIS_PORT} get testkey
              echo "Sleeping for ${INTERVAL_SECONDS} seconds..."
              sleep ${INTERVAL_SECONDS}
            done
        resources:
          {{- toYaml .Values.client.resources | nindent 10 }}
{{- end }} 