apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "redis-app.fullname" . }}
  labels:
    {{- include "redis-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  replicas: {{ .Values.server.replicaCount }}
  selector:
    matchLabels:
      {{- include "redis-app.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: server
  template:
    metadata:
      labels:
        {{- include "redis-app.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: server
    spec:
      {{- if .Values.server.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.server.imagePullSecrets | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "redis-app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: redis
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}"
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
          ports:
            - name: redis
              containerPort: {{ .Values.server.service.port }}
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: redis
          readinessProbe:
            tcpSocket:
              port: redis
          resources:
            {{- toYaml .Values.server.resources | nindent 12 }} 