apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis-app.fullname" . }}
  labels:
    {{- include "redis-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "redis-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server 