/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Authenticate a user
         * @description Authenticate a user
         */
        post: operations["postAuthLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/console/available-network-interfaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List available network interfaces
         * @description List available network interfaces
         */
        get: operations["getConsoleListAvailableNetworkInterfaces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the health of the API
         * @description get the health of the API
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/kubernetes/install/app-preflights/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run install app preflight checks
         * @description Run install app preflight checks using current app configuration
         */
        post: operations["postKubernetesInstallRunAppPreflights"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/kubernetes/install/app-preflights/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get app preflight status for install
         * @description Get the current status and results of app preflight checks for install
         */
        get: operations["getKubernetesInstallAppPreflightsStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/kubernetes/install/app/config/template": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Template the app config with provided values
         * @description Template the app config with provided values and return the templated config
         */
        post: operations["postKubernetesInstallTemplateAppConfig"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/kubernetes/install/app/config/values": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the app config values
         * @description Get the current app config values
         */
        get: operations["getKubernetesInstallAppConfigValues"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Set the app config values
         * @description Set the app config values with partial updates
         */
        patch: operations["patchKubernetesInstallAppConfigValues"];
        trace?: never;
    };
    "/kubernetes/install/app/install": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Install the app
         * @description Install the app using current configuration
         */
        post: operations["postKubernetesInstallApp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/kubernetes/install/app/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get app install status
         * @description Get the current status of app installation
         */
        get: operations["getKubernetesInstallAppStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/kubernetes/install/infra/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Setup infra components
         * @description Setup infra components
         */
        post: operations["postKubernetesInstallSetupInfra"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/kubernetes/install/infra/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the status of the infra
         * @description Get the current status of the infra
         */
        get: operations["getKubernetesInstallInfraStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/kubernetes/install/installation/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the Kubernetes installation config
         * @description get the Kubernetes installation config
         */
        get: operations["getKubernetesInstallInstallationConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/kubernetes/install/installation/configure": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Configure the Kubernetes installation for install
         * @description configure the Kubernetes installation for install
         */
        post: operations["postKubernetesInstallConfigureInstallation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/kubernetes/install/installation/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get installation configuration status for install
         * @description Get the current status of the installation configuration for install
         */
        get: operations["getKubernetesInstallInstallationStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/kubernetes/upgrade/app-preflights/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run upgrade app preflight checks
         * @description Run upgrade app preflight checks using current app configuration
         */
        post: operations["postKubernetesUpgradeRunAppPreflights"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/kubernetes/upgrade/app-preflights/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get app preflight status for upgrade
         * @description Get the current status and results of app preflight checks for upgrade
         */
        get: operations["getKubernetesUpgradeAppPreflightsStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/kubernetes/upgrade/app/config/template": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Template app config for upgrade
         * @description Template the app configuration with values for upgrade
         */
        post: operations["postKubernetesUpgradeAppConfigTemplate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/kubernetes/upgrade/app/config/values": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the app config values for upgrade
         * @description Get the current app config values for upgrade
         */
        get: operations["getKubernetesUpgradeAppConfigValues"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Set the app config values for upgrade
         * @description Set the app config values with partial updates for upgrade
         */
        patch: operations["patchKubernetesUpgradeAppConfigValues"];
        trace?: never;
    };
    "/kubernetes/upgrade/app/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get app upgrade status
         * @description Get the current status of app upgrade
         */
        get: operations["getKubernetesUpgradeAppStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/kubernetes/upgrade/app/upgrade": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upgrade the app
         * @description Upgrade the app using current configuration
         */
        post: operations["postKubernetesUpgradeApp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/linux/install/airgap/process": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Process the airgap bundle
         * @description Process the airgap bundle for install
         */
        post: operations["postLinuxInstallProcessAirgap"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/linux/install/airgap/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the status of the airgap processing
         * @description Get the current status of the airgap processing for install
         */
        get: operations["getLinuxInstallAirgapStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/linux/install/app-preflights/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run install app preflight checks
         * @description Run install app preflight checks using current app configuration
         */
        post: operations["postLinuxInstallRunAppPreflights"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/linux/install/app-preflights/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get app preflight status for install
         * @description Get the current status and results of app preflight checks for install
         */
        get: operations["getLinuxInstallAppPreflightsStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/linux/install/app/config/template": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Template the app config with provided values
         * @description Template the app config with provided values and return the templated config
         */
        post: operations["postLinuxInstallTemplateAppConfig"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/linux/install/app/config/values": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the app config values
         * @description Get the current app config values
         */
        get: operations["getLinuxInstallAppConfigValues"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Set the app config values
         * @description Set the app config values with partial updates
         */
        patch: operations["patchLinuxInstallAppConfigValues"];
        trace?: never;
    };
    "/linux/install/app/install": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Install the app
         * @description Install the app using current configuration
         */
        post: operations["postLinuxInstallApp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/linux/install/app/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get app install status
         * @description Get the current status of app installation
         */
        get: operations["getLinuxInstallAppStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/linux/install/host-preflights/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run install host preflight checks
         * @description Run install host preflight checks using installation config and client-provided data
         */
        post: operations["postLinuxInstallRunHostPreflights"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/linux/install/host-preflights/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get host preflight status for install
         * @description Get the current status and results of host preflight checks for install
         */
        get: operations["getLinuxInstallHostPreflightsStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/linux/install/infra/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Setup infra components
         * @description Setup infra components
         */
        post: operations["postLinuxInstallSetupInfra"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/linux/install/infra/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the status of the infra
         * @description Get the current status of the infra
         */
        get: operations["getLinuxInstallInfraStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/linux/install/installation/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the installation config
         * @description get the installation config
         */
        get: operations["getLinuxInstallInstallationConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/linux/install/installation/configure": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Configure the installation for install
         * @description configure the installation for install
         */
        post: operations["postLinuxInstallConfigureInstallation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/linux/install/installation/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get installation configuration status for install
         * @description Get the current status of the installation configuration for install
         */
        get: operations["getLinuxInstallInstallationStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/linux/kurl-migration/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the installation config for kURL migration
         * @description Get the installation config extracted from kURL merged with EC defaults
         */
        get: operations["getKURLMigrationInstallationConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/linux/kurl-migration/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start a migration from kURL to Embedded Cluster
         * @description Start a migration from kURL to Embedded Cluster with the provided configuration
         */
        post: operations["postStartMigration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/linux/kurl-migration/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the status of the kURL migration
         * @description Get the current status and progress of the kURL migration
         */
        get: operations["getKURLMigrationStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/linux/upgrade/airgap/process": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Process the airgap bundle
         * @description Process the airgap bundle for upgrade
         */
        post: operations["postLinuxUpgradeProcessAirgap"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/linux/upgrade/airgap/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the status of the airgap processing
         * @description Get the current status of the airgap processing for upgrade
         */
        get: operations["getLinuxUpgradeAirgapStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/linux/upgrade/app-preflights/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run upgrade app preflight checks
         * @description Run upgrade app preflight checks using current app configuration
         */
        post: operations["postLinuxUpgradeRunAppPreflights"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/linux/upgrade/app-preflights/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get app preflight status for upgrade
         * @description Get the current status and results of app preflight checks for upgrade
         */
        get: operations["getLinuxUpgradeAppPreflightsStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/linux/upgrade/app/config/template": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Template app config for upgrade
         * @description Template the app configuration with values for upgrade
         */
        post: operations["postLinuxUpgradeAppConfigTemplate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/linux/upgrade/app/config/values": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the app config values for upgrade
         * @description Get the current app config values for upgrade
         */
        get: operations["getLinuxUpgradeAppConfigValues"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Set the app config values for upgrade
         * @description Set the app config values with partial updates for upgrade
         */
        patch: operations["patchLinuxUpgradeAppConfigValues"];
        trace?: never;
    };
    "/linux/upgrade/app/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get app upgrade status
         * @description Get the current status of app upgrade
         */
        get: operations["getLinuxUpgradeAppStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/linux/upgrade/app/upgrade": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upgrade the app
         * @description Upgrade the app using current configuration
         */
        post: operations["postLinuxUpgradeApp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/linux/upgrade/infra/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the status of the infra upgrade
         * @description Get the current status of the infrastructure upgrade
         */
        get: operations["getLinuxUpgradeInfraStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/linux/upgrade/infra/upgrade": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upgrade the infrastructure
         * @description Upgrade the infrastructure (k0s, addons, extensions)
         */
        post: operations["postLinuxUpgradeInfra"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "github_com_replicatedhq_embedded-cluster_api_types.Health": {
            status: string;
        };
        "github_com_replicatedhq_kotskinds_multitype.BoolOrString": Record<string, never>;
        "types.APIError": {
            errors?: components["schemas"]["types.APIError"][];
            field?: string;
            message: string;
            statusCode?: number;
        };
        "types.Airgap": {
            logs: string;
            status: components["schemas"]["types.Status"];
        };
        "types.AppConfig": {
            groups: components["schemas"]["v1beta1.ConfigGroup"][];
        };
        "types.AppConfigValue": {
            data?: string;
            dataPlaintext?: string;
            default?: string;
            filename?: string;
            repeatableItem?: string;
            value: string;
        };
        "types.AppConfigValues": {
            [key: string]: components["schemas"]["types.AppConfigValue"];
        };
        "types.AppConfigValuesResponse": {
            values: components["schemas"]["types.AppConfigValues"];
        };
        "types.AppInstall": {
            logs: string;
            status: components["schemas"]["types.Status"];
        };
        "types.AppUpgrade": {
            logs: string;
            status: components["schemas"]["types.Status"];
        };
        "types.AuthRequest": {
            password: string;
        };
        "types.AuthResponse": {
            token: string;
        };
        "types.GetListAvailableNetworkInterfacesResponse": {
            networkInterfaces: string[];
        };
        "types.Infra": {
            components: components["schemas"]["types.InfraComponent"][];
            logs: string;
            status: components["schemas"]["types.Status"];
        };
        "types.InfraComponent": {
            name: string;
            status: components["schemas"]["types.Status"];
        };
        "types.InstallAppPreflightsStatusResponse": {
            allowIgnoreAppPreflights: boolean;
            hasStrictAppPreflightFailures: boolean;
            output?: components["schemas"]["types.PreflightsOutput"];
            status: components["schemas"]["types.Status"];
            titles: string[];
        };
        "types.InstallAppRequest": {
            ignoreAppPreflights: boolean;
        };
        "types.InstallHostPreflightsStatusResponse": {
            allowIgnoreHostPreflights: boolean;
            output?: components["schemas"]["types.PreflightsOutput"];
            status?: components["schemas"]["types.Status"];
            titles: string[];
        };
        /**
         * @description Phase is the current phase of the kURL migration process
         * @example Discovery
         * @enum {string}
         */
        "types.KURLMigrationPhase": "Discovery" | "Preparation" | "ECInstall" | "DataTransfer" | "Completed";
        /**
         * @description State is the current state of the kURL migration
         * @example InProgress
         * @enum {string}
         */
        "types.KURLMigrationState": "NotStarted" | "InProgress" | "Completed" | "Failed";
        /** @description Current status and progress of a kURL migration */
        "types.KURLMigrationStatusResponse": {
            /**
             * @description Error contains the error message if the kURL migration failed
             * @example
             */
            error?: string;
            /**
             * @description Message is a user-facing message describing the current status
             * @example Discovering kURL cluster configuration
             */
            message: string;
            phase: components["schemas"]["types.KURLMigrationPhase"];
            /**
             * @description Progress is the completion percentage (0-100)
             * @example 25
             */
            progress: number;
            state: components["schemas"]["types.KURLMigrationState"];
        };
        "types.KubernetesInstallationConfig": {
            adminConsolePort?: number;
            httpProxy?: string;
            httpsProxy?: string;
            noProxy?: string;
        };
        "types.KubernetesInstallationConfigResponse": {
            defaults: components["schemas"]["types.KubernetesInstallationConfig"];
            resolved: components["schemas"]["types.KubernetesInstallationConfig"];
            values: components["schemas"]["types.KubernetesInstallationConfig"];
        };
        "types.LinuxInfraSetupRequest": {
            ignoreHostPreflights: boolean;
        };
        /** @description Config contains optional installation configuration that will be merged with defaults */
        "types.LinuxInstallationConfig": {
            dataDirectory?: string;
            globalCidr?: string;
            httpProxy?: string;
            httpsProxy?: string;
            localArtifactMirrorPort?: number;
            networkInterface?: string;
            noProxy?: string;
            podCidr?: string;
            serviceCidr?: string;
        };
        "types.LinuxInstallationConfigResponse": {
            defaults: components["schemas"]["types.LinuxInstallationConfig"];
            resolved: components["schemas"]["types.LinuxInstallationConfig"];
            values: components["schemas"]["types.LinuxInstallationConfig"];
        };
        "types.PatchAppConfigValuesRequest": {
            values: components["schemas"]["types.AppConfigValues"];
        };
        "types.PostInstallRunHostPreflightsRequest": {
            isUi: boolean;
        };
        "types.PreflightsOutput": {
            fail: components["schemas"]["types.PreflightsRecord"][];
            pass: components["schemas"]["types.PreflightsRecord"][];
            warn: components["schemas"]["types.PreflightsRecord"][];
        };
        "types.PreflightsRecord": {
            message: string;
            strict: boolean;
            title: string;
        };
        /** @description Request body for starting a migration from kURL to Embedded Cluster */
        "types.StartKURLMigrationRequest": {
            config?: components["schemas"]["types.LinuxInstallationConfig"];
            transferMode: components["schemas"]["types.TransferMode"];
        };
        /** @description Response returned when a kURL migration is successfully started */
        "types.StartKURLMigrationResponse": {
            /**
             * @description Message is a user-facing message about the kURL migration status
             * @example kURL migration started successfully
             */
            message: string;
            /**
             * @description MigrationID is the unique identifier for this migration
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            migrationId: string;
        };
        /**
         * @example Succeeded
         * @enum {string}
         */
        "types.State": "Pending" | "Running" | "Succeeded" | "Failed";
        "types.Status": {
            description: string;
            lastUpdated: string;
            state: components["schemas"]["types.State"];
        };
        "types.TemplateAppConfigRequest": {
            values: components["schemas"]["types.AppConfigValues"];
        };
        /**
         * @description TransferMode specifies whether to copy or move data during kURL migration
         * @example copy
         * @enum {string}
         */
        "types.TransferMode": "copy" | "move";
        "types.UpgradeAppPreflightsStatusResponse": {
            allowIgnoreAppPreflights: boolean;
            hasStrictAppPreflightFailures: boolean;
            output?: components["schemas"]["types.PreflightsOutput"];
            status: components["schemas"]["types.Status"];
            titles: string[];
        };
        "types.UpgradeAppRequest": {
            ignoreAppPreflights: boolean;
        };
        "v1beta1.ConfigChildItem": {
            default: components["schemas"]["github_com_replicatedhq_kotskinds_multitype.BoolOrString"];
            name: string;
            recommended: boolean;
            title: string;
            value: components["schemas"]["github_com_replicatedhq_kotskinds_multitype.BoolOrString"];
        };
        "v1beta1.ConfigGroup": {
            description: string;
            items: components["schemas"]["v1beta1.ConfigItem"][];
            name: string;
            title: string;
            when: string;
        };
        "v1beta1.ConfigItem": {
            affix: string;
            countByGroup: {
                [key: string]: number;
            };
            data: string;
            default: components["schemas"]["github_com_replicatedhq_kotskinds_multitype.BoolOrString"];
            error: string;
            filename: string;
            help_text: string;
            hidden: boolean;
            items: components["schemas"]["v1beta1.ConfigChildItem"][];
            minimumCount: number;
            multi_value: string[];
            multiple: boolean;
            name: string;
            readonly: boolean;
            recommended: boolean;
            repeatable: boolean;
            required: boolean;
            templates: components["schemas"]["v1beta1.RepeatTemplate"][];
            title: string;
            type: string;
            validation: components["schemas"]["v1beta1.ConfigItemValidation"];
            value: components["schemas"]["github_com_replicatedhq_kotskinds_multitype.BoolOrString"];
            valuesByGroup: components["schemas"]["v1beta1.ValuesByGroup"];
            when: string;
            write_once: boolean;
        };
        "v1beta1.ConfigItemValidation": {
            regex: components["schemas"]["v1beta1.RegexValidator"];
        };
        "v1beta1.GroupValues": {
            [key: string]: string;
        };
        "v1beta1.RegexValidator": {
            message: string;
            pattern: string;
        };
        "v1beta1.RepeatTemplate": {
            apiVersion: string;
            kind: string;
            name: string;
            namespace: string;
            yamlPath: string;
        };
        "v1beta1.ValuesByGroup": {
            [key: string]: components["schemas"]["v1beta1.GroupValues"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    postAuthLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Auth Request */
        requestBody: {
            content: {
                "application/json": components["schemas"]["types.AuthRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.AuthResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.APIError"];
                };
            };
        };
    };
    getConsoleListAvailableNetworkInterfaces: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.GetListAvailableNetworkInterfacesResponse"];
                };
            };
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["github_com_replicatedhq_embedded-cluster_api_types.Health"];
                };
            };
        };
    };
    postKubernetesInstallRunAppPreflights: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.InstallAppPreflightsStatusResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.APIError"];
                };
            };
        };
    };
    getKubernetesInstallAppPreflightsStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.InstallAppPreflightsStatusResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.APIError"];
                };
            };
        };
    };
    postKubernetesInstallTemplateAppConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Template App Config Request */
        requestBody: {
            content: {
                "application/json": components["schemas"]["types.TemplateAppConfigRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.AppConfig"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.APIError"];
                };
            };
        };
    };
    getKubernetesInstallAppConfigValues: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.AppConfigValuesResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.APIError"];
                };
            };
        };
    };
    patchKubernetesInstallAppConfigValues: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Patch App Config Values Request */
        requestBody: {
            content: {
                "application/json": components["schemas"]["types.PatchAppConfigValuesRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.AppConfigValuesResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.APIError"];
                };
            };
        };
    };
    postKubernetesInstallApp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Install App Request */
        requestBody: {
            content: {
                "application/json": components["schemas"]["types.InstallAppRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.AppInstall"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.APIError"];
                };
            };
        };
    };
    getKubernetesInstallAppStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.AppInstall"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.APIError"];
                };
            };
        };
    };
    postKubernetesInstallSetupInfra: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.Infra"];
                };
            };
        };
    };
    getKubernetesInstallInfraStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.Infra"];
                };
            };
        };
    };
    getKubernetesInstallInstallationConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.KubernetesInstallationConfigResponse"];
                };
            };
        };
    };
    postKubernetesInstallConfigureInstallation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Installation config */
        requestBody: {
            content: {
                "application/json": components["schemas"]["types.KubernetesInstallationConfig"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.Status"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.APIError"];
                };
            };
        };
    };
    getKubernetesInstallInstallationStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.Status"];
                };
            };
        };
    };
    postKubernetesUpgradeRunAppPreflights: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.UpgradeAppPreflightsStatusResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.APIError"];
                };
            };
        };
    };
    getKubernetesUpgradeAppPreflightsStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.UpgradeAppPreflightsStatusResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.APIError"];
                };
            };
        };
    };
    postKubernetesUpgradeAppConfigTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Template App Config Request */
        requestBody: {
            content: {
                "application/json": components["schemas"]["types.TemplateAppConfigRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.AppConfig"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.APIError"];
                };
            };
        };
    };
    getKubernetesUpgradeAppConfigValues: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.AppConfigValuesResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.APIError"];
                };
            };
        };
    };
    patchKubernetesUpgradeAppConfigValues: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Patch App Config Values Request */
        requestBody: {
            content: {
                "application/json": components["schemas"]["types.PatchAppConfigValuesRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.AppConfigValuesResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.APIError"];
                };
            };
        };
    };
    getKubernetesUpgradeAppStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.AppUpgrade"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.APIError"];
                };
            };
        };
    };
    postKubernetesUpgradeApp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Upgrade App Request */
        requestBody: {
            content: {
                "application/json": components["schemas"]["types.UpgradeAppRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.AppUpgrade"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.APIError"];
                };
            };
        };
    };
    postLinuxInstallProcessAirgap: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.Airgap"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.APIError"];
                };
            };
        };
    };
    getLinuxInstallAirgapStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.Airgap"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.APIError"];
                };
            };
        };
    };
    postLinuxInstallRunAppPreflights: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.InstallAppPreflightsStatusResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.APIError"];
                };
            };
        };
    };
    getLinuxInstallAppPreflightsStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.InstallAppPreflightsStatusResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.APIError"];
                };
            };
        };
    };
    postLinuxInstallTemplateAppConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Template App Config Request */
        requestBody: {
            content: {
                "application/json": components["schemas"]["types.TemplateAppConfigRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.AppConfig"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.APIError"];
                };
            };
        };
    };
    getLinuxInstallAppConfigValues: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.AppConfigValuesResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.APIError"];
                };
            };
        };
    };
    patchLinuxInstallAppConfigValues: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Patch App Config Values Request */
        requestBody: {
            content: {
                "application/json": components["schemas"]["types.PatchAppConfigValuesRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.AppConfigValuesResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.APIError"];
                };
            };
        };
    };
    postLinuxInstallApp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Install App Request */
        requestBody: {
            content: {
                "application/json": components["schemas"]["types.InstallAppRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.AppInstall"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.APIError"];
                };
            };
        };
    };
    getLinuxInstallAppStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.AppInstall"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.APIError"];
                };
            };
        };
    };
    postLinuxInstallRunHostPreflights: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Post Install Run Host Preflights Request */
        requestBody: {
            content: {
                "application/json": components["schemas"]["types.PostInstallRunHostPreflightsRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.InstallHostPreflightsStatusResponse"];
                };
            };
        };
    };
    getLinuxInstallHostPreflightsStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.InstallHostPreflightsStatusResponse"];
                };
            };
        };
    };
    postLinuxInstallSetupInfra: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Infra Setup Request */
        requestBody: {
            content: {
                "application/json": components["schemas"]["types.LinuxInfraSetupRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.Infra"];
                };
            };
        };
    };
    getLinuxInstallInfraStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.Infra"];
                };
            };
        };
    };
    getLinuxInstallInstallationConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.LinuxInstallationConfigResponse"];
                };
            };
        };
    };
    postLinuxInstallConfigureInstallation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Installation config */
        requestBody: {
            content: {
                "application/json": components["schemas"]["types.LinuxInstallationConfig"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.Status"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.APIError"];
                };
            };
        };
    };
    getLinuxInstallInstallationStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.Status"];
                };
            };
        };
    };
    getKURLMigrationInstallationConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.LinuxInstallationConfigResponse"];
                };
            };
        };
    };
    postStartMigration: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Start kURL Migration Request */
        requestBody: {
            content: {
                "application/json": components["schemas"]["types.StartKURLMigrationRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.StartKURLMigrationResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.APIError"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.APIError"];
                };
            };
        };
    };
    getKURLMigrationStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.KURLMigrationStatusResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.APIError"];
                };
            };
        };
    };
    postLinuxUpgradeProcessAirgap: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.Airgap"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.APIError"];
                };
            };
        };
    };
    getLinuxUpgradeAirgapStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.Airgap"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.APIError"];
                };
            };
        };
    };
    postLinuxUpgradeRunAppPreflights: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.UpgradeAppPreflightsStatusResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.APIError"];
                };
            };
        };
    };
    getLinuxUpgradeAppPreflightsStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.UpgradeAppPreflightsStatusResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.APIError"];
                };
            };
        };
    };
    postLinuxUpgradeAppConfigTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Template App Config Request */
        requestBody: {
            content: {
                "application/json": components["schemas"]["types.TemplateAppConfigRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.AppConfig"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.APIError"];
                };
            };
        };
    };
    getLinuxUpgradeAppConfigValues: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.AppConfigValuesResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.APIError"];
                };
            };
        };
    };
    patchLinuxUpgradeAppConfigValues: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Patch App Config Values Request */
        requestBody: {
            content: {
                "application/json": components["schemas"]["types.PatchAppConfigValuesRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.AppConfigValuesResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.APIError"];
                };
            };
        };
    };
    getLinuxUpgradeAppStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.AppUpgrade"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.APIError"];
                };
            };
        };
    };
    postLinuxUpgradeApp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Upgrade App Request */
        requestBody: {
            content: {
                "application/json": components["schemas"]["types.UpgradeAppRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.AppUpgrade"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.APIError"];
                };
            };
        };
    };
    getLinuxUpgradeInfraStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.Infra"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.APIError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.APIError"];
                };
            };
        };
    };
    postLinuxUpgradeInfra: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.Infra"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.APIError"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.APIError"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.APIError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["types.APIError"];
                };
            };
        };
    };
}
