alpine_version = 3.17
alpine_patch_version = $(alpine_version).3
golang_buildimage=docker.io/library/golang:$(go_version)-alpine$(alpine_version)
go_version = 1.20.3
kubernetes_version = 1.27.1
helm_version = 3.11.1
etcd_version = 3.5.8

smoketests := \
	check-noderole-no-taints

#	check-basic \
