---
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    open-pull-requests-limit: 25
    schedule:
      interval: "weekly"
      day: "saturday"
    labels:
      - "dependencies"
      - "go"
      - "type::chore"
    groups:
      security:
        update-types:
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "dependencies"
      - "github-actions"
      - "type::chore"
    schedule:
      interval: "weekly"
      day: "saturday"
