---
version: 2
updates:
  - package-ecosystem: "gomod"
    directories:
      - "/"
      - "/kinds/"
      - "/utils/"
      - "/dagger/"
    open-pull-requests-limit: 10
    schedule:
      interval: "weekly"
      day: "saturday"
    labels:
      - "dependencies"
      - "go"
      - "type::chore"
    groups:
      security:
        update-types:
          - "patch"
      k8s.io:
        patterns:
          - "k8s.io/*"
      aws-sdk-go-v2:
        patterns:
          - "github.com/aws/aws-sdk-go-v2*"

  - package-ecosystem: "npm"
    directories:
      - "/web/"
      - "/e2e/playwright/"
    open-pull-requests-limit: 10
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "01:00"
    labels:
      - "dependabot"
      - "javascript"
      - "type::chore"
    groups:
      security:
        update-types:
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "dependencies"
      - "github-actions"
      - "type::chore"
    schedule:
      interval: "weekly"
      day: "saturday"
