{{- if .Values.metrics.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
{{- with (include "embedded-cluster-operator.labels" $ | fromYaml) }}
  labels: {{- toYaml . | nindent 4 }}
{{- end }}
  name: {{ printf "%s-metrics-reader" (include "embedded-cluster-operator.fullname" $) | trunc 63 | trimAll "-" }}
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
{{- end }}
