apiVersion: v1
kind: ConfigMap
metadata:
  name: embedded-cluster-troubleshoot-goldpinger
  labels:
    troubleshoot.sh/kind: support-bundle
    {{- with (include "embedded-cluster-operator.labels" $ | fromYaml) }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  support-bundle-spec: |
    apiVersion: troubleshoot.sh/v1beta2
    kind: SupportBundle
    metadata:
      name: embedded-cluster-troubleshoot-goldpinger
      labels:
        troubleshoot.sh/kind: support-bundle
    spec:
      collectors:
      - goldpinger:
          namespace: {{ .Release.Namespace }}
          image: {{ .Values.goldpingerImage }}
          podLaunchOptions:
            image: {{ .Values.utilsImage }}
            namespace: {{ .Release.Namespace }}
          exclude: {{ .Values.isAirgap }}
      analyzers:
      - goldpinger:
          exclude: {{ .Values.isAirgap }}
