apiVersion: v1
kind: ServiceAccount
metadata:
{{- with (include "embedded-cluster-operator.labels" $ | fromYaml) }}
  labels: {{- toYaml . | nindent 4 }}
{{- end }}
  name: {{ (include "embedded-cluster-operator.serviceAccountName" $) | trunc 63 | trimAll "-" }}
