apiVersion: v1
kind: ConfigMap
metadata:
  name: embedded-cluster-lam-service-config
  labels:
    troubleshoot.sh/kind: support-bundle
    {{- with (include "embedded-cluster-operator.labels" $ | fromYaml) }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  support-bundle-spec: |
    apiVersion: troubleshoot.sh/v1beta2
    kind: SupportBundle
    metadata:
      name: embedded-cluster-lam-service-config
      labels:
        troubleshoot.sh/kind: support-bundle
    spec:
      collectors:
        - runDaemonSet:
            name: "local-artifact-mirror-service-config"
            namespace: embedded-cluster
            podSpec:
              containers:
              - image: {{ .Values.utilsImage }}
                imagePullPolicy: Always
                args: ["chroot","/host","cat","/etc/systemd/system/local-artifact-mirror.service.d/embedded-cluster.conf"]
                name: debugger
                resources: {}
                terminationMessagePath: /dev/termination-log
                terminationMessagePolicy: File
                volumeMounts:
                - mountPath: /host
                  name: host-root
              dnsPolicy: ClusterFirst
              enableServiceLinks: true
              hostIPC: true
              hostNetwork: true
              hostPID: true
              securityContext:
                runAsUser: 0
              tolerations:
              - operator: Exists
              volumes:
              - hostPath:
                  path: /
                  type: ""
                name: host-root
