{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
{{- with (include "embedded-cluster-operator.labels" $ | fromYaml) }}
  labels: {{- toYaml . | nindent 4 }}
{{- end }}
  name: {{ printf "%s-metrics" (include "embedded-cluster-operator.fullname" $) | trunc 63 | trimAll "-" }}
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector: {{- include "embedded-cluster-operator.selectorLabels" $ | nindent 4 }}
{{- end }}
