version: "2"
linters:
  default: none
  enable:
    - govet
    - ineffassign
    - nolintlint
    - staticcheck
<<<<<<< HEAD
    # - unused

    # Our own extras:
    - gofmt
    # We disable nolintlint on purpose given there's directives only applicable on latest which fail on previous release
    # branches
    # - nolintlint # lints nolint directives
    # - revive

linters-settings:
  govet:
    # These govet checks are disabled by default, but they're useful.
    enable:
    - nilness
    - reflectvaluecompare
    - sortslice
    - unusedwrite
  unused:
    field-writes-are-uses: false
    exported-fields-are-used: false
    # parameters-are-used: false
    local-variables-are-used: false

=======
  settings:
    govet:
      enable:
        - nilness
        - reflectvaluecompare
        - sortslice
        - unusedwrite
    unused:
      field-writes-are-uses: false
      exported-fields-are-used: false
      local-variables-are-used: false
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
>>>>>>> release-2.7.3+k8s-1.31
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
