version: "2"
linters:
  default: none
  enable:
    - govet
    - ineffassign
    - nolintlint
    - staticcheck
  settings:
    govet:
      enable:
        - nilness
        - reflectvaluecompare
        - sortslice
        - unusedwrite
    unused:
      field-writes-are-uses: false
      exported-fields-are-used: false
      local-variables-are-used: false
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
