project_name: helmvm
release:
  github:
    owner: replicatedhq
    name: helmvm
builds:
  - id: helmvm
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    hooks:
      pre: make static
    main: ./cmd
