name: E2E CMX Setup
description: Setup steps for CMX-based e2e testing environment
inputs:
  github-token:
    description: 'the ci github token used to install the replicated cli'
    required: true

runs:
  using: composite
  steps:
  - name: Install replicated CLI
    shell: bash
    env:
      GH_TOKEN: ${{ inputs.github-token }}
    run: |
      gh release download --repo replicatedhq/replicated --pattern '*_linux_amd64.tar.gz' --output /tmp/replicated.tar.gz --clobber
      tar -xzf /tmp/replicated.tar.gz -C /tmp
      mv /tmp/replicated /usr/local/bin/replicated
  - name: Setup SSH
    shell: bash
    run: |
      mkdir -p ~/.ssh
      ssh-keygen -t rsa -b 4096 -C "deploy@replicated.com" -f ~/.ssh/id_rsa -N ""
      chmod 600 ~/.ssh/id_rsa
