# adapted from:
#   https://github.com/chainguard-images/images/blob/3cdccf0c57ee1ab83c7f02f7d2aaa1edfbf5dfcb/images/velero/config/main.tf
contents:
  repositories:
    - https://packages.wolfi.dev/os
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
  packages:
    - glibc
    - ld-linux
    - libcrypt1
    - velero~${PACKAGE_VERSION}
    - velero-compat~${PACKAGE_VERSION}
    - velero-restore-helper~${PACKAGE_VERSION}

accounts:
  groups:
    - groupname: nonroot
      gid: 65532
  users:
    - username: nonroot
      uid: 65532
      gid: 65532
  run-as: 65532

entrypoint:
  command: /usr/bin/velero
