apiVersion: troubleshoot.sh/v1beta2
kind: HostPreflight
metadata:
  name: ec-cluster-preflight
spec:
  collectors:
    - http:
        collectorName: http-replicated-app
        get:
          url: https://replicated.app
          timeout: 5s
          tls:
            cacert: '{{ .PrivateCA }}'
        proxy:
          url: '{{ .HTTPSProxy }}'
  analyzers:
    - http:
        checkName: API Access
        collectorName: http-replicated-app
        outcomes:
          - fail:
              when: error
              message: >
                Error connecting to {{ .ReplicatedAPIURL }}.
                Ensure your firewall is properly configured, and use the --http-proxy, --https-proxy,
                and --no-proxy flags if there is a proxy server.
                The static IP addresses for {{ .ReplicatedAPIURL }} are
                162.159.133.41 and 162.159.134.41.
          - pass:
              when: 'statusCode == 200'
              message: 'Connected to {{ .ReplicatedAPIURL }}'
          - fail:
              message: >
                Error connecting to {{ .ReplicatedAPIURL }}.
                Ensure your firewall is properly configured, and use the --http-proxy, --https-proxy,
                and --no-proxy flags if there is a proxy server.
                The static IP addresses for {{ .ReplicatedAPIURL }} are
                162.159.133.41 and 162.159.134.41.
