apiVersion: troubleshoot.sh/v1beta2
kind: HostPreflight
metadata:
  name: ec-cluster-preflight
spec:
  collectors:
    - diskUsage:
        collectorName: root-disk-usage
        path: /
    - diskUsage:
        collectorName: embedded-cluster-path-usage
        path: /var/lib/embedded-cluster
    - diskUsage:
        collectorName: k0s-path-usage
        path: /var/lib/k0s
    - diskUsage:
        collectorName: openebs-path-usage
        path: /opt/openebs
    - diskUsage:
        collectorName: tmp-path-usage
        path: /tmp
    - memory: {}
    - cpu: {}
    - time: {}
    - ipv4Interfaces: {}
    - kernelConfigs: {}
  analyzers:
    - cpu:
        checkName: 'Number of CPUs in the system'
        outcomes:
          - fail:
              when: 'count < 2'
              message: At least 2 CPU cores is required
          - pass:
              message: This node has at least 2 CPU cores
    - diskUsage:
        checkName: embedded-cluster path usage
        collectorName: embedded-cluster-path-usage
        outcomes:
          - fail:
              when: 'total < 40Gi'
              message: The filesystem at the path /var/lib/embedded-cluster has less than 40Gi of total space
          - pass:
              message: The filesystem at the path /var/lib/embedded-cluster has sufficient space
    - diskUsage:
        checkName: k0s path usage
        collectorName: k0s-path-usage
        outcomes:
          - fail:
              when: 'total < 40Gi'
              message: The filesystem at the path /var/lib/k0s has less than 40Gi of total space
          - fail:
              when: 'used/total > 80%'
              message: The filesystem at the path /var/lib/k0s is more than 80% full
          - pass:
              message: The filesystem at the path /var/lib/k0s has sufficient space
    - diskUsage:
        checkName: openebs path usage
        collectorName: openebs-path-usage
        outcomes:
          - fail:
              when: 'total < 5Gi'
              message: The filesystem at the path /opt/openebs has less than 5Gi of total space
          - pass:
              message: The filesystem at the path /opt/openebs has sufficient space
    - diskUsage:
        checkName: tmp path usage
        collectorName: tmp-path-usage
        outcomes:
          - fail:
              when: 'total < 5Gi'
              message: The filesystem at the path /tmp has less than 5Gi of total space
          - pass:
              message: The filesystem at the path /tmp has sufficient space
    - memory:
        checkName: Amount of memory on the system
        outcomes:
          - fail:
              when: '< 2G'
              message: At least 2G of memory is recommended
          - pass:
              message: The system has at least 2G of memory
    - ipv4Interfaces:
        outcomes:
          - fail:
              when: 'count == 0'
              message: No IPv4 interfaces detected
          - pass:
              when: 'count >= 1'
              message: IPv4 interface detected
    - time:
        checkName: 'Time synchronization'
        outcomes:
          - fail:
              when: 'ntp == unsynchronized+inactive'
              message: 'System clock is not synchronized'
          - fail:
              when: 'ntp == unsynchronized+active'
              message: System clock not yet synchronized
          - pass:
              when: 'ntp == synchronized+active'
              message: 'System clock is synchronized'
    - kernelConfigs:
        checkName: "Control Group support kernel config"
        selectedConfigs:
          - CONFIG_CGROUPS=my
        outcomes:
          - pass:
              message: "CGROUPS (Control Group support) kernel config is available"
          - fail:
              message: "CGROUPS (Control Group support) kernel config is missing"
    - kernelConfigs:
        checkName: "Freezer cgroup subsystem kernel config"
        selectedConfigs:
          - CONFIG_CGROUP_FREEZER=my
        outcomes:
          - pass:
              message: "CGROUP_FREEZER (Freezer cgroup subsystem) kernel config is available"
          - fail:
              message: "CGROUP_FREEZER (Freezer cgroup subsystem) kernel config is missing"
    - kernelConfigs:
        checkName: "PIDs cgroup subsystem kernel config"
        selectedConfigs:
          - CONFIG_CGROUP_PIDS=my
        outcomes:
          - pass:
              message: "CGROUP_PIDS (PIDs cgroup subsystem) kernel config is available"
          - fail:
              message: "CGROUP_PIDS (PIDs cgroup subsystem) kernel config is missing"
    - kernelConfigs:
        checkName: "Device controller for cgroups kernel config"
        selectedConfigs:
          - CONFIG_CGROUP_DEVICE=my
        outcomes:
          - pass:
              message: "CGROUP_DEVICE (Device controller for cgroups) kernel config is available"
          - fail:
              message: "CGROUP_DEVICE (Device controller for cgroups) kernel config is missing"
    - kernelConfigs:
        checkName: "Cpuset support kernel config"
        selectedConfigs:
          - CONFIG_CPUSETS=my
        outcomes:
          - pass:
              message: "CPUSETS (Cpuset support) kernel config is available"
          - fail:
              message: "CPUSETS (Cpuset support) kernel config is missing"
    - kernelConfigs:
        checkName: "Simple CPU accounting cgroup subsystem kernel config"
        selectedConfigs:
          - CONFIG_CGROUP_CPUACCT=my
        outcomes:
          - pass:
              message: "CGROUP_CPUACCT (Simple CPU accounting cgroup subsystem) kernel config is available"
          - fail:
              message: "CGROUP_CPUACCT (Simple CPU accounting cgroup subsystem) kernel config is missing"
    - kernelConfigs:
        checkName: "Memory Resource Controller for Control Groups kernel config"
        selectedConfigs:
          - CONFIG_MEMCG=my
        outcomes:
          - pass:
              message: "MEMCG (Memory Resource Controller for Control Groups) kernel config is available"
          - fail:
              message: "MEMCG (Memory Resource Controller for Control Groups) kernel config is missing"
    - kernelConfigs:
        checkName: "Group CPU scheduler kernel config"
        selectedConfigs:
          - CONFIG_CGROUP_SCHED=my
        outcomes:
          - pass:
              message: "CGROUP_SCHED (Group CPU scheduler) kernel config is available"
          - fail:
              message: "CGROUP_SCHED (Group CPU scheduler) kernel config is missing"
    - kernelConfigs:
        checkName: "Group scheduling for SCHED_OTHER kernel config"
        selectedConfigs:
          - CONFIG_FAIR_GROUP_SCHED=my
        outcomes:
          - pass:
              message: "FAIR_GROUP_SCHED (Group scheduling for SCHED_OTHER) kernel config is available"
          - fail:
              message: "FAIR_GROUP_SCHED (Group scheduling for SCHED_OTHER) kernel config is missing"
    - kernelConfigs:
        checkName: "Namespaces support kernel config"
        selectedConfigs:
          - CONFIG_NAMESPACES=my
        outcomes:
          - pass:
              message: "NAMESPACES (Namespaces support) kernel config is available"
          - fail:
              message: "NAMESPACES (Namespaces support) kernel config is missing"
    - kernelConfigs:
        checkName: "UTS namespace kernel config"
        selectedConfigs:
          - CONFIG_UTS_NS=my
        outcomes:
          - pass:
              message: "UTS_NS (UTS namespace) kernel config is available"
          - fail:
              message: "UTS_NS (UTS namespace) kernel config is missing"
    - kernelConfigs:
        checkName: "IPC namespace kernel config"
        selectedConfigs:
          - CONFIG_IPC_NS=my
        outcomes:
          - pass:
              message: "IPC_NS (IPC namespace) kernel config is available"
          - fail:
              message: "IPC_NS (IPC namespace) kernel config is missing"
    - kernelConfigs:
        checkName: "PID namespace kernel config"
        selectedConfigs:
          - CONFIG_PID_NS=my
        outcomes:
          - pass:
              message: "PID_NS (PID namespace) kernel config is available"
          - fail:
              message: "PID_NS (PID namespace) kernel config is missing"
    - kernelConfigs:
        checkName: "Network namespace kernel config"
        selectedConfigs:
          - CONFIG_NET_NS=my
        outcomes:
          - pass:
              message: "NET_NS (Network namespace) kernel config is available"
          - fail:
              message: "NET_NS (Network namespace) kernel config is missing"
    - kernelConfigs:
        checkName: "Networking support kernel config"
        selectedConfigs:
          - CONFIG_NET=my
        outcomes:
          - pass:
              message: "NET (Networking support) kernel config is available"
          - fail:
              message: "NET (Networking support) kernel config is missing"
    - kernelConfigs:
        checkName: "TCP/IP networking kernel config"
        selectedConfigs:
          - CONFIG_INET=my
        outcomes:
          - pass:
              message: "INET (TCP/IP networking) kernel config is available"
          - fail:
              message: "INET (TCP/IP networking) kernel config is missing"
    - kernelConfigs:
        checkName: "Network packet filtering framework (Netfilter) kernel config"
        selectedConfigs:
          - CONFIG_NETFILTER=my
        outcomes:
          - pass:
              message: "NETFILTER (Network packet filtering framework (Netfilter)) kernel config is available"
          - fail:
              message: "NETFILTER (Network packet filtering framework (Netfilter)) kernel config is missing"
    - kernelConfigs:
        checkName: "Netfilter Xtables support kernel config"
        selectedConfigs:
          - CONFIG_NETFILTER_XTABLES=my
        outcomes:
          - pass:
              message: "NETFILTER_XTABLES (Netfilter Xtables support) kernel config is available"
          - fail:
              message: "NETFILTER_XTABLES (Netfilter Xtables support) kernel config is missing"
    - kernelConfigs:
        checkName: "REDIRECT target support kernel config"
        selectedConfigs:
          - CONFIG_NETFILTER_XT_TARGET_REDIRECT=my
        outcomes:
          - pass:
              message: "NETFILTER_XT_TARGET_REDIRECT (REDIRECT target support) kernel config is available"
          - fail:
              message: "NETFILTER_XT_TARGET_REDIRECT (REDIRECT target support) kernel config is missing"
    - kernelConfigs:
        checkName: "NETFILTER_XT_MATCH_COMMENT (\"comment\" match support) kernel config"
        selectedConfigs:
          - CONFIG_NETFILTER_XT_MATCH_COMMENT=my
        outcomes:
          - pass:
              message: "NETFILTER_XT_MATCH_COMMENT (\"comment\" match support) kernel config is available"
          - fail:
              message: "NETFILTER_XT_MATCH_COMMENT (\"comment\" match support) kernel config is missing"
    - kernelConfigs:
        checkName: "The Extended 4 (ext4) filesystem kernel config"
        selectedConfigs:
          - CONFIG_EXT4_FS=my
        outcomes:
          - pass:
              message: "EXT4_FS (The Extended 4 (ext4) filesystem) kernel config is available"
          - fail:
              message: "EXT4_FS (The Extended 4 (ext4) filesystem) kernel config is missing"
    - kernelConfigs:
        checkName: "/proc file system support kernel config"
        selectedConfigs:
          - CONFIG_PROC_FS=my
        outcomes:
          - pass:
              message: "PROC_FS (/proc file system support) kernel config is available"
          - fail:
              message: "PROC_FS (/proc file system support) kernel config is missing"
