package:
  name: local-artifact-mirror
  version: "0.0.1" # our versioning is not compatible with apk
  epoch: 0
  description: Local Artifact Mirror
  copyright:
    - license: Apache-2.0

environment:
  contents:
    repositories:
      - https://apk.cve0.io
    keyring:
      - https://apk.cve0.io/key/cve0-signing.rsa.pub
    packages:
      - bash
      - busybox
      - build-base
      - bash
      - git
      - go
      - ca-certificates-bundle
  environment:
    GOCACHE: /cache/melange/gocache
    GOMODCACHE: /cache/melange/gomodcache
    K0S_MINOR_VERSION: ${K0S_MINOR_VERSION}
    GOPROXY: 'https://proxy.golang.org,direct'
    GOSUMDB: 'sum.golang.org'

pipeline:
  - runs: |
      set -exuo pipefail

      rm -rf bin
      mkdir -p ${{targets.contextdir}}/usr/bin
      mkdir -p ${{targets.contextdir}}/usr/local/bin

      make -C local-artifact-mirror build
      cp local-artifact-mirror/bin/local-artifact-mirror-$(go env GOOS)-$(go env GOARCH) ${{targets.contextdir}}/usr/bin/local-artifact-mirror
      # support for legacy path
      ln -s /usr/bin/local-artifact-mirror ${{targets.contextdir}}/usr/local/bin/local-artifact-mirror
  - uses: strip
