apiVersion: kots.io/v1beta1
kind: Config
metadata:
  name: test-config
spec:
  groups:
    - name: config-items
      title: Config Items
      items:
        - name: label
          type: label
          title: |
            ## Config Items

            The values set in the config items below will populate the `configitems` ConfigMap in the app (nginx-app).

            ---

        - name: text
          title: Text
          type: text
          default: "default text"
          help_text: "Help text of a **_Text* config item type"

        - name: password
          title: Password
          type: password
          default: "default password"
          help_text: "Help text of a **_Password_** config item type"

        - name: textarea
          title: Textarea
          type: textarea
          default: "default textarea"
          help_text: "Help text of a **_Textarea_** config item type"

        - name: checkbox
          title: Checkbox
          type: bool
          default: "0"
          help_text: "Help text of a **_Checkbox_** config item type"

        - name: dropdown
          title: Dropdown
          type: dropdown
          help_text: "Help text of a **_Dropdown_** config item type"
          items:
            - name: opt1
              title: Option 1
            - name: opt2
              title: Option 2
            - name: opt3
              title: Option 3
          default: opt1

        - name: radio
          title: Radio
          type: radio
          help_text: "Help text of a *Radio* config item type"
          items:
            - name: opt1
              title: Option 1
            - name: opt2
              title: Option 2
            - name: opt3
              title: Option 3
          default: opt1

        - name: file
          title: File
          type: file
          help_text: "Help text of a **_File_** config item type"

    - name: markdown-items
      title: Markdown Items
      items:
        - name: label
          type: label
          title: |
            ## Markdown Items

            This group is dedicated to markdown support.

            ---

            # H1 Heading

            ## H2 Heading

            ### H3 Heading

            This is a paragraph with **bold**, *italic*, and ~~strikethrough~~ text.  
            You can also combine them: **_bold and italic_**, or ~~**bold strikethrough**~~.

            Here's a link to [Replicated Docs](https://docs.replicated.com/).

            And here's an image (if your renderer supports images):

            ![Test Image](https://docs.replicated.com/images/logo-replicated-red.png)

            ---

            ### Unordered List

            - Item one
            - Item two
              - Nested item
                - Deeply nested item

            ---

            ### Ordered List

            1. First item
            2. Second item
               1. Sub-item
               2. Another sub-item

            ---

            ### Inline Code

            Use the `console.log()` function to print to the console.

            ---

            ### Code Block

            ```
            function greet(name) {
              return `Hello, ${name}!`;
            }
            ```

            ---

            ### Blockquote

            > This is a blockquote.  
            > It can span multiple lines.  
            > And include **bold** or *italic* text.

            ---

            ### Horizontal Rule

            ---

            ### Table

            | Feature        | Supported? |
            |----------------|------------|
            | **Bold**       | ✅         |
            | *Italic*       | ✅         |
            | `Code`         | ✅         |
            | ~~Strikethrough~~ | ✅      |

            ---

            This line contains a <u>custom underline</u> using raw HTML.
