apiVersion: kots.io/v1beta1
kind: Config
metadata:
  name: test-config
spec:
  groups:
    - name: cert-example-settings
      title: My Cert Example Config
      items:
        - name: hostname
          title: Hostname
          help_text: Enter a DNS hostname to use as the cert's CN.
          type: text

        - name: tls_json
          title: TLS JSON
          type: textarea
          hidden: true
          default: |-
            repl{{ $ca := genCA (ConfigOption "hostname") 365 }}
            repl{{ $tls := dict "ca" $ca }}
            repl{{ $cert := genSignedCert (ConfigOption "hostname") (list ) (list (ConfigOption "hostname")) 365 $ca }}
            repl{{ $_ := set $tls "cert" $cert }}
            repl{{ toJson $tls }}

        - name: tls_ca
          title: Signing Authority
          type: textarea
          default: repl{{ fromJson (ConfigOption "tls_json") | dig "ca" "Cert" "" }}

        - name: tls_cert
          title: TLS Cert
          type: textarea
          default: repl{{ fromJson (ConfigOption "tls_json") | dig "cert" "Cert" "" }}

        - name: tls_key
          title: TLS Key
          type: textarea
          default: repl{{ fromJson (ConfigOption "tls_json") | dig "cert" "Key" "" }}

        - name: api_hostname
          title: API Hostname
          help_text: Enter the hostname for the API certificate.
          type: text

        - name: api_tls_json
          title: API TLS JSON
          type: textarea
          hidden: true
          default: |-
            repl{{ $ca := genCA (ConfigOption "api_hostname") 365 }}
            repl{{ $tls := dict "ca" $ca }}
            repl{{ $cert := genSignedCert (ConfigOption "api_hostname") (list ) (list (ConfigOption "api_hostname")) 365 $ca }}
            repl{{ $_ := set $tls "cert" $cert }}
            repl{{ toJson $tls }}

        - name: api_tls_ca
          title: API Signing Authority
          type: textarea
          default: repl{{ fromJson (ConfigOption "api_tls_json") | dig "ca" "Cert" "" }}

        - name: api_tls_cert
          title: API TLS Cert
          type: textarea
          default: repl{{ fromJson (ConfigOption "api_tls_json") | dig "cert" "Cert" "" }}

        - name: api_tls_key
          title: API TLS Key
          type: textarea
          default: repl{{ fromJson (ConfigOption "api_tls_json") | dig "cert" "Key" "" }}

        - name: db_hostname
          title: Database Hostname
          help_text: Enter the hostname for the database certificate.
          type: text

        - name: db_tls_json
          title: Database TLS JSON
          type: textarea
          hidden: true
          default: |-
            repl{{ $ca := genCA (ConfigOption "db_hostname") 365 }}
            repl{{ $tls := dict "ca" $ca }}
            repl{{ $cert := genSignedCert (ConfigOption "db_hostname") (list ) (list (ConfigOption "db_hostname")) 365 $ca }}
            repl{{ $_ := set $tls "cert" $cert }}
            repl{{ toJson $tls }}

        - name: db_tls_ca
          title: Database Signing Authority
          type: textarea
          default: repl{{ fromJson (ConfigOption "db_tls_json") | dig "ca" "Cert" "" }}

        - name: db_tls_cert
          title: Database TLS Cert
          type: textarea
          default: repl{{ fromJson (ConfigOption "db_tls_json") | dig "cert" "Cert" "" }}

        - name: db_tls_key
          title: Database TLS Key
          type: textarea
          default: repl{{ fromJson (ConfigOption "db_tls_json") | dig "cert" "Key" "" }}

        - name: ingress_hostname
          title: Ingress Hostname
          help_text: Enter the hostname for the ingress certificate.
          type: text

        - name: ingress_tls_json
          title: Ingress TLS JSON
          type: textarea
          hidden: true
          default: |-
            repl{{ $ca := genCA (ConfigOption "ingress_hostname") 365 }}
            repl{{ $tls := dict "ca" $ca }}
            repl{{ $cert := genSignedCert (ConfigOption "ingress_hostname") (list ) (list (ConfigOption "ingress_hostname")) 365 $ca }}
            repl{{ $_ := set $tls "cert" $cert }}
            repl{{ toJson $tls }}

        - name: ingress_tls_ca
          title: Ingress Signing Authority
          type: textarea
          default: repl{{ fromJson (ConfigOption "ingress_tls_json") | dig "ca" "Cert" "" }}

        - name: ingress_tls_cert
          title: Ingress TLS Cert
          type: textarea
          default: repl{{ fromJson (ConfigOption "ingress_tls_json") | dig "cert" "Cert" "" }}

        - name: ingress_tls_key
          title: Ingress TLS Key
          type: textarea
          default: repl{{ fromJson (ConfigOption "ingress_tls_json") | dig "cert" "Key" "" }}

        - name: registry_hostname
          title: Registry Hostname
          help_text: Enter the hostname for the container registry certificate.
          type: text

        - name: registry_tls_json
          title: Registry TLS JSON
          type: textarea
          hidden: true
          default: |-
            repl{{ $ca := genCA (ConfigOption "registry_hostname") 365 }}
            repl{{ $tls := dict "ca" $ca }}
            repl{{ $cert := genSignedCert (ConfigOption "registry_hostname") (list ) (list (ConfigOption "registry_hostname")) 365 $ca }}
            repl{{ $_ := set $tls "cert" $cert }}
            repl{{ toJson $tls }}

        - name: registry_tls_ca
          title: Registry Signing Authority
          type: textarea
          default: repl{{ fromJson (ConfigOption "registry_tls_json") | dig "ca" "Cert" "" }}

        - name: registry_tls_cert
          title: Registry TLS Cert
          type: textarea
          default: repl{{ fromJson (ConfigOption "registry_tls_json") | dig "cert" "Cert" "" }}

        - name: registry_tls_key
          title: Registry TLS Key
          type: textarea
          default: repl{{ fromJson (ConfigOption "registry_tls_json") | dig "cert" "Key" "" }}

    - name: config-items
      title: Config Items
      items:
        - name: label_intro
          type: label
          title: |
            The values set in the config items below will populate the `configitems` ConfigMap in the app (nginx-app).

        - name: label_text
          type: label
          title: |
            ## Text Items
            ---

        - name: text_simple
          title: Simple Text
          type: text
          help_text: "Help text of a simple **_Text_** config item type"

        - name: text_with_value
          title: Text with value
          type: text
          value: "value text"
          help_text: "Help text of a **_Text_** config item type **_with value_**"

        - name: text_with_default
          title: Text with default value
          type: text
          default: "default text"
          help_text: "Help text of a **_Text_** config item type **_with default value_**"

        - name: text_required
          title: Text marked required
          type: text
          required: true
          help_text: "Help text of a **_Text_** config item type **_marked required_**"

        - name: text_with_regex
          title: Text with Email Validation
          type: text
          help_text: "Must be a valid email address"
          validation:
            regex:
              pattern: '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
              message: Please enter a valid email address

        - name: text_required_with_regex
          title: Required Email Address
          type: text
          required: true
          help_text: "Required field with email validation"
          validation:
            regex:
              pattern: '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
              message: Please enter a valid email address

        - name: text_with_regex_no_message
          title: Text with Regex (Default Message)
          type: text
          help_text: "Must contain only lowercase letters"
          validation:
            regex:
              pattern: '^[a-z]+$'

        - name: label_password
          type: label
          title: |
            ## Password Items
            ---

        - name: password_simple
          title: Simple Password
          type: password
          help_text: "Help text of a simple **_Password_** config item type"

        - name: password_with_default
          title: Password with default value
          type: password
          default: "default password"
          help_text: "Help text of a **_Password_** config item type **_with default value_**"

        - name: password_required
          title: Password marked required
          type: password
          required: true
          help_text: "Help text of a **_Password_** config item type **_marked required_**"

        - name: password_with_regex
          title: Strong Password
          type: password
          help_text: "Must be at least 8 characters with uppercase, lowercase, and number"
          validation:
            regex:
              pattern: '^(?=.*[A-Z])(?=.*[a-z])(?=.*\d).{8,}$'
              message: Password must be at least 8 characters with uppercase, lowercase, and number

        - name: label_textarea
          type: label
          title: |
            ## Textarea Items
            ---

        - name: textarea_simple
          title: Simple Textarea
          type: textarea
          help_text: "Help text of a simple **_Textarea_** config item type"

        - name: textarea_with_default
          title: Textarea with default value
          type: textarea
          default: "default textarea"
          help_text: "Help text of a **_Textarea_** config item type **_with default value_**"

        - name: textarea_required
          title: Textarea marked required
          type: textarea
          required: true
          help_text: "Help text of a **_Textarea_** config item type **_marked required_**"

        - name: textarea_with_regex
          title: JSON Configuration
          type: textarea
          help_text: "Must be valid JSON format"
          validation:
            regex:
              pattern: '^\{.*\}$'
              message: Must be a valid JSON object

        - name: label_checkbox
          type: label
          title: |
            ## Checkbox/Bool Items
            ---

        - name: checkbox_simple
          title: Simple Checkbox
          type: bool
          help_text: "Help text of a simple **_Checkbox_** config item type"

        - name: checkbox_with_default
          title: Checkbox with default value
          type: bool
          default: "1"
          help_text: "Help text of a **_Checkbox_** config item type **_with default value_**"

        - name: checkbox_required
          title: Checkbox marked required
          type: bool
          required: true
          help_text: "Help text of a **_Checkbox_** config item type **_marked required_**"

        - name: heading_dropdown
          type: heading
          title: Dropdown Configuration

        - name: dropdown_simple
          title: Simple Dropdown
          type: dropdown
          help_text: "Help text of a simple **_Dropdown_** config item type"
          items:
            - name: dropdown_simple_opt1
              title: Option 1
            - name: dropdown_simple_opt2
              title: Option 2

        - name: dropdown_with_default
          title: Dropdown with default value
          type: dropdown
          help_text: "Help text of a **_Dropdown_** config item type **_with default value_**"
          items:
            - name: dropdown_with_default_opt1
              title: Option 1
            - name: dropdown_with_default_opt2
              title: Option 2
          default: dropdown_with_default_opt1

        - name: dropdown_required
          title: Dropdown marked required
          type: dropdown
          required: true
          help_text: "Help text of a **_Dropdown_** config item type **_marked required_**"
          items:
            - name: dropdown_required_opt1
              title: Option 1
            - name: dropdown_required_opt2
              title: Option 2

        - name: heading_selectone
          type: heading
          title: Select One Configuration

        - name: selectone_simple
          title: Simple Select One (renders as radio)
          type: select_one
          help_text: "Help text of a simple **_Select One_** config item type (backward compatible with radio)"
          items:
            - name: selectone_simple_opt1
              title: Option 1
            - name: selectone_simple_opt2
              title: Option 2

        - name: selectone_with_default
          title: Select One with default value
          type: select_one
          help_text: "Help text of a **_Select One_** config item type **_with default value_**"
          items:
            - name: selectone_with_default_opt1
              title: Option 1
            - name: selectone_with_default_opt2
              title: Option 2
          default: selectone_with_default_opt2

        - name: heading_radio
          type: heading
          title: Radio Configuration

        - name: label_radio
          type: label
          title: |
            ## Radio Items
            ---

        - name: radio_simple
          title: Simple Radio
          type: radio
          help_text: "Help text of a simple **_Radio_** config item type"
          items:
            - name: radio_simple_opt1
              title: Option 1
            - name: radio_simple_opt2
              title: Option 2

        - name: radio_with_default
          title: Radio with default value
          type: radio
          help_text: "Help text of a **_Radio_** config item type **_with default value_**"
          items:
            - name: radio_with_default_opt1
              title: Option 1
            - name: radio_with_default_opt2
              title: Option 2
          default: radio_with_default_opt1

        - name: radio_required
          title: Radio marked required
          type: radio
          required: true
          help_text: "Help text of a **_Radio_** config item type **_marked required_**"
          items:
            - name: radio_required_opt1
              title: Option 1
            - name: radio_required_opt2
              title: Option 2

        - name: label_file
          type: label
          title: |
            ## File Items
            ---

        - name: file_simple
          title: Simple File
          type: file
          help_text: "Help text of a simple **_File_** config item type"

        - name: file_with_default
          title: File with default value
          type: file
          default: "default file"
          help_text: "Help text of a **_File_** config item type **_with default value_**"
          filename: "default-file.txt"

        - name: file_required
          title: File marked required
          type: file
          required: true
          help_text: "Help text of a **_File_** config item type **_marked required_**"

        - name: heading_readonly
          type: heading
          title: ReadOnly Configuration

        - name: readonly_text
          title: ReadOnly Text Field
          type: text
          value: "This value cannot be changed"
          readonly: true
          help_text: "This is a **_readonly text field_** - you cannot edit it"

        - name: readonly_textarea
          title: ReadOnly Textarea
          type: textarea
          value: "This is a readonly textarea.\nIt has multiple lines.\nBut you cannot edit it."
          readonly: true
          help_text: "This is a **_readonly textarea_**"

        - name: readonly_checkbox
          title: ReadOnly Checkbox
          type: bool
          value: "1"
          readonly: true
          help_text: "This checkbox is checked and **_readonly_**"

        - name: readonly_radio
          title: ReadOnly Radio
          type: radio
          value: radio_readonly_opt2
          readonly: true
          help_text: "This radio group is **_readonly_** with option 2 selected"
          items:
            - name: radio_readonly_opt1
              title: Option 1
            - name: radio_readonly_opt2
              title: Option 2

        - name: readonly_dropdown
          title: ReadOnly Dropdown
          type: dropdown
          value: dropdown_readonly_opt2
          readonly: true
          help_text: "This dropdown is **_readonly_** with Option 2 selected"
          items:
            - name: dropdown_readonly_opt1
              title: Option 1
            - name: dropdown_readonly_opt2
              title: Option 2

        - name: hidden_required
          title: Hidden required
          type: text
          hidden: true
          required: true
          value: '{{repl ConfigOption "text_required" }}'

    - name: markdown-items
      title: Markdown Items
      items:
        - name: markdown_toggle
          title: Toggle Markdown Items
          type: bool
          help_text: "Help text of a **_Checkbox_** config item type"
          default: "1"

        - name: label_markdown
          type: label
          when: '{{repl ConfigOptionEquals "markdown_toggle" "1" }}'
          title: |
            ## Markdown Items

            This group is dedicated to markdown support.

            ---

            # H1 Heading

            ## H2 Heading

            ### H3 Heading

            This is a paragraph with **bold**, *italic*, and ~~strikethrough~~ text.  
            You can also combine them: **_bold and italic_**, or ~~**bold strikethrough**~~.

            Here's a link to [Replicated Docs](https://docs.replicated.com/).

            And here's an image (if your renderer supports images):

            ![Test Image](https://docs.replicated.com/images/logo-replicated-red.png)

            ---

            ### Unordered List

            - Item one
            - Item two
              - Nested item
                - Deeply nested item

            ---

            ### Ordered List

            1. First item
            2. Second item
               1. Sub-item
               2. Another sub-item

            ---

            ### Inline Code

            Use the `console.log()` function to print to the console.

            ---

            ### Code Block

            ```
            function greet(name) {
              return `Hello, ${name}!`;
            }
            ```

            ---

            ### Blockquote

            > This is a blockquote.  
            > It can span multiple lines.  
            > And include **bold** or *italic* text.

            ---

            ### Horizontal Rule

            ---

            ### Table

            | Feature        | Supported? |
            |----------------|------------|
            | **Bold**       | ✅         |
            | *Italic*       | ✅         |
            | `Code`         | ✅         |
            | ~~Strikethrough~~ | ✅      |

            ---

            This line contains a <u>custom underline</u> using raw HTML.
