apiVersion: kots.io/v1beta2
kind: HelmChart
metadata:
  name: nginx-app
spec:
  chart:
    name: nginx-app
    chartVersion: 0.1.0
  namespace: nginx-app
  values:
    preflight:
      enabled: true
    server:
      image:
        repository: repl{{ HasLocalRegistry | ternary LocalRegistryHost "ec-e2e-proxy.testcluster.net" }}/repl{{ HasLocalRegistry | ternary LocalRegistryNamespace "proxy/embedded-cluster-smoke-test-staging-app/us-east4-docker.pkg.dev/replicated-qa/ec-smoke-test" }}/nginx
      service:
        type: ClusterIP
        port: 80
      replicaCount: 1
      imagePullSecrets:
        - name: '{{repl ImagePullSecretName }}'
      env:
        - name: PRIVATE_CA_CONFIGMAP
          value: 'repl{{ PrivateCACert }}'
        - name: SSL_CERT_DIR
          value: "/etc/ssl/certs"
    client:
      enabled: true
      image:
        repository: repl{{ HasLocalRegistry | ternary LocalRegistryHost "ec-e2e-proxy.testcluster.net" }}/repl{{ HasLocalRegistry | ternary LocalRegistryNamespace "proxy/embedded-cluster-smoke-test-staging-app/us-east4-docker.pkg.dev/replicated-qa/ec-smoke-test" }}/curl
      replicaCount: 1
      intervalSeconds: 60
      imagePullSecrets:
        - name: '{{repl ImagePullSecretName }}'
    replicated:
      enabled: true
      image:
        registry: repl{{ HasLocalRegistry | ternary LocalRegistryHost "ec-e2e-proxy.testcluster.net" }}
        repository: repl{{ HasLocalRegistry | ternary LocalRegistryNamespace "anonymous/registry.replicated.com/library" }}/replicated-sdk-image
      imagePullSecrets:
        - name: '{{repl ImagePullSecretName }}'
    configItemsConfigMapData:
      # Registry template functions verification
      has_local_registry: repl{{ HasLocalRegistry }}
      local_registry_host: repl{{ HasLocalRegistry | ternary LocalRegistryHost "fallback-host" }}
      local_registry_namespace: repl{{ HasLocalRegistry | ternary LocalRegistryNamespace "fallback-namespace" }}
      local_registry_address: repl{{ HasLocalRegistry | ternary LocalRegistryAddress "fallback-address" }}
      image_pull_secret_name: repl{{ HasLocalRegistry | ternary ImagePullSecretName "fallback-secret" }}

      # Text items
      text_simple: repl{{ ConfigOption "text_simple" }}
      text_with_default: repl{{ ConfigOption "text_with_default" }}
      text_required: repl{{ ConfigOption "text_required" }}

      # Password items
      password_simple: repl{{ ConfigOption "password_simple" }}
      password_with_default: repl{{ ConfigOption "password_with_default" }}
      password_required: repl{{ ConfigOption "password_required" }}

      # Textarea items
      textarea_simple: repl{{ ConfigOption "textarea_simple" }}
      textarea_with_default: repl{{ ConfigOption "textarea_with_default" }}
      textarea_required: repl{{ ConfigOption "textarea_required" }}

      # Checkbox/Bool items
      checkbox_simple: repl{{ ConfigOption "checkbox_simple" }}
      checkbox_with_default: repl{{ ConfigOption "checkbox_with_default" }}
      checkbox_required: repl{{ ConfigOption "checkbox_required" }}

      # Dropdown items
      dropdown_simple: repl{{ ConfigOption "dropdown_simple" }}
      dropdown_with_default: repl{{ ConfigOption "dropdown_with_default" }}
      dropdown_required: repl{{ ConfigOption "dropdown_required" }}

      # Radio items
      radio_simple: repl{{ ConfigOption "radio_simple" }}
      radio_with_default: repl{{ ConfigOption "radio_with_default" }}
      radio_required: repl{{ ConfigOption "radio_required" }}

      # File items
      file_simple: repl{{ ConfigOptionFilename "file_simple" }}
      file_with_default: repl{{ ConfigOptionFilename "file_with_default" }}
      file_required: repl{{ ConfigOptionFilename "file_required" }}

  optionalValues:
    - when: '{{repl ne PrivateCACert "" }}'
      recursiveMerge: true
      values:
        server:
          volumeMounts:
            - name: ca-certs
              mountPath: /etc/ssl/certs
              readOnly: true
          volumes:
            - name: ca-certs
              configMap:
                name: 'repl{{ PrivateCACert }}'

  builder:
    replicated:
      enabled: true
