# source: https://github.com/chainguard-images/images/blob/387659a22a0d41a04801e3507a2238d2f1622906/images/calico/configs/latest.cni.apko.yaml
contents:
  repositories:
    - https://packages.wolfi.dev/os
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
  packages:
    - calico-cni=${PACKAGE_VERSION}
    - calico-cni-compat=${PACKAGE_VERSION}

accounts:
  groups:
    - groupname: nonroot
      gid: 65532
  users:
    - username: nonroot
      uid: 65532
      gid: 65532
  run-as: 0

entrypoint:
  command: /opt/cni/bin/install

environment:
  PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/cni/bin
