apiVersion: troubleshoot.sh/v1beta2
kind: HostPreflight
metadata:
  name: ec-resolv-conf-preflight
spec:
  collectors:
    - run:
        collectorName: resolv.conf
        command: 'sh'
        args: ['-c', 'cat {{if .RootDir}}{{ .RootDir }}{{else}}/{{end}}etc/resolv.conf']
  analyzers:
    - textAnalyze:
        checkName: Resolver Configuration
        fileName: host-collectors/run-host/resolv.conf.txt
        regex: '(?m)^nameserver\s+(localhost|127\.0\.0\.1|::1|::ffff:127\.0\.0\.1)'
        outcomes:
          - fail:
              when: "true"
              message: "Local DNS resolver detected. Remove the localhost, 127.0.0.1, ::1, and/or ::ffff:127.0.0.1 nameserver entries from resolv.conf."
          - pass:
              when: "false"
              message: "No local nameserver entries detected in resolv.conf"
    - textAnalyze:
        checkName: Nameserver Configuration
        fileName: host-collectors/run-host/resolv.conf.txt
        regex: '(?m)^nameserver\s+(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}|[0-9a-fA-F]*:[0-9a-fA-F:]+)\s*$'
        outcomes:
          - fail:
              when: "false"
              message: "No nameservers are configured in resolv.conf. Update resolv.conf to include at least one nameserver."
          - pass:
              when: "true"
              message: "Nameservers are configured in resolv.conf."
