apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pixee-enterprise-server.name" . }}-preflight
  labels: {{- include "pixee-enterprise-server.labels" . | nindent 4 }}
    troubleshoot.sh/kind: preflight
stringData:
  preflight.yaml: |- {{- include "troubleshoot.preflight.pixee-enterprise-server" . | nindent 4 }}
---
{{- define "troubleshoot.preflight.pixee-enterprise-server" -}}
apiVersion: troubleshoot.sh/v1beta2
kind: Preflight
metadata:
  name: {{ include "pixee-enterprise-server.name" . }}-preflight
spec:
  collectors:
    {{- include "troubleshoot.collectors.pixee-enterprise-server.cluster" .  | nindent 4 -}}
    {{- if and .Values.global.pixee.ai.enabled .Values.global.pixee.ai.azure.enabled -}}
    {{- include "troubleshoot.collectors.pixee-enterprise-server.azure-openai" .  | nindent 4 }}
    {{- end }}
    {{- if and .Values.global.pixee.ai.enabled .Values.global.pixee.ai.openai.enabled -}}
    {{- include "troubleshoot.collectors.pixee-enterprise-server.openai" .  | nindent 4 }}
    {{- end }}
  analyzers:
    {{- include "troubleshoot.analyzers.pixee-enterprise-server.cluster" .  | nindent 4 -}}
    {{- if and .Values.global.pixee.ai.enabled .Values.global.pixee.ai.azure.enabled -}}
    {{- include "troubleshoot.analyzers.pixee-enterprise-server.azure-openai" .  | nindent 4 }}
    {{- end }}
    {{- if and .Values.global.pixee.ai.enabled .Values.global.pixee.ai.openai.enabled -}}
    {{- include "troubleshoot.analyzers.pixee-enterprise-server.openai" .  | nindent 4 }}
    {{- end }}
{{- end -}}