apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pixee-enterprise-server.name" . }}-support-bundle
  labels: {{- include "pixee-enterprise-server.labels" . | nindent 4 }}
    troubleshoot.sh/kind: support-bundle
stringData:
  support-bundle-spec: |- {{- include "troubleshoot.supportBundle.pixee-enterprise-server" . | nindent 4 }}
---
{{- define "troubleshoot.supportBundle.pixee-enterprise-server" -}}
apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: {{ include "pixee-enterprise-server.name" . }}-support-bundle
spec:
  collectors:
    {{ include "troubleshoot.collectors.pixee-enterprise-server.cluster" . | nindent 4 }}
    {{- if and .Values.global.pixee.ai.enabled .Values.global.pixee.ai.azure.enabled -}}
    {{- include "troubleshoot.collectors.pixee-enterprise-server.azure-openai" .  | nindent 4 }}
    {{- end }}
    {{- if and .Values.global.pixee.ai.enabled .Values.global.pixee.ai.openai.enabled -}}
    {{- include "troubleshoot.collectors.pixee-enterprise-server.openai" .  | nindent 4 }}
    {{- end }}
  analyzers:
    {{ include "troubleshoot.analyzers.pixee-enterprise-server.cluster" . | nindent 4 }}
    {{- if .Values.global.pixee.objectStore.embedded }}
    {{ include "troubleshoot.analyzers.pixee-enterprise-server.cluster.minio" . | nindent 4 }}
    {{- end }}
    {{- if and .Values.global.pixee.ai.enabled .Values.global.pixee.ai.azure.enabled -}}
    {{- include "troubleshoot.analyzers.pixee-enterprise-server.azure-openai" .  | nindent 4 }}
    {{- end }}
    {{- if and .Values.global.pixee.ai.enabled .Values.global.pixee.ai.openai.enabled -}}
    {{- include "troubleshoot.analyzers.pixee-enterprise-server.openai" .  | nindent 4 }}
    {{- end }}
{{- end -}}
