# source: https://github.com/chainguard-images/images/blob/bea234042585fd6db129bc2c836aad4937f55799/images/envoy/config/main.tf
contents:
  repositories:
    - https://packages.wolfi.dev/os
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
  packages:
    - envoy~${PACKAGE_VERSION}
    - envoy-config~${PACKAGE_VERSION}
    - envoy-oci-entrypoint~${PACKAGE_VERSION}
    - su-exec

accounts:
  groups:
    - groupname: nonroot
      gid: 65532
  users:
    - username: nonroot
      uid: 65532
      gid: 65532
  run-as: 65532

paths:
  - path: /etc/envoy
    type: directory
    uid: 65532
    gid: 65532
    permissions: 0o755

entrypoint:
  command: /var/lib/envoy/init/envoy-entrypoint.sh
