contents:
  repositories:
    - https://packages.wolfi.dev/os
    - ./operator-package/packages/
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    - ./operator-package/melange.rsa.pub
  packages:
    - embedded-cluster-operator  # This is expected to be built locally by `melange`.
    - ca-certificates-bundle

accounts:
  groups:
    - groupname: nonroot
      gid: 65532
  users:
    - username: nonroot
      uid: 65532
      gid: 65532
  run-as: 65532

environment:
  VERSION: ${PACKAGE_VERSION}

entrypoint:
  command: /manager
