apiVersion: embeddedcluster.replicated.com/v1beta1
kind: Config
metadata:
  name: "test-cluster-config"
  annotations:
    kots.io/exclude: "true"
spec:
  version: "1.29.2+ec.0"
  roles:
    controller:
      labels:
        controller-test-label: controller-test-label-value
      name: controller-node
    custom:
      - labels:
          abc-test-label: abc-test-label-value
          abc-test-label-two: abc-test-label-value-2
        name: web
      - labels:
          xyz-test-label: xyz-value
        name: backend
      - labels:
          elasticsearch-node-role: main
        name: elasticsearch-main
  unsupportedOverrides:
    k0s: |
      config:
        spec:
          api:
            extraArgs:
              service-node-port-range: 80-32767
  extensions:
    helm:
      repositories:
        - name: ingress-nginx
          url: https://kubernetes.github.io/ingress-nginx
      charts:
        - name: ingress-nginx
          chartname: ingress-nginx/ingress-nginx
          namespace: ingress-nginx
          version: "4.9.1"
          values: |
            controller:
              service:
                type: NodePort
                nodePorts:
                  http: "80"
                  https: "443"
                annotations:
                  test-chart-annotation: test-chart-value
