apiVersion: troubleshoot.sh/v1beta2
kind: Preflight
metadata:
  name: preflight-checks
  annotations:
    kots.io/exclude: "true"
spec:
  analyzers:
    - clusterVersion:
        outcomes:
          - fail:
              when: "< 1.28.0"
              message: The application requires Kubernetes 1.28.0 or later, and recommends 1.29.0 or later.
              uri: https://www.kubernetes.io
          - warn:
              when: "< 1.29.0"
              message: Your cluster meets the minimum version of Kubernetes, but we recommend you update to 1.29.0 or later.
              uri: https://kubernetes.io
          - pass:
              message: Your cluster meets the recommended and required versions of Kubernetes.
