name: E2E Local Setup
description: Setup steps for local e2e testing environment
runs:
  using: composite
  steps:
  - name: Remove MS repo
    shell: bash
    run: |
      apt-add-repository --list
      sudo apt-add-repository -y -r deb [arch=amd64,arm64,armhf] https://packages.microsoft.com/ubuntu/22.04/prod jammy main
      apt-add-repository --list
  - name: Move Docker aside
    shell: bash
    run: |
      sudo systemctl stop docker
      sudo iptables -F
      sudo iptables -P FORWARD ACCEPT
  - name: Install and Configure LXD
    shell: bash
    run: |
      sudo lxd init --auto
      sudo snap set lxd daemon.group=adm
      sudo snap restart lxd
      sudo lxd waitready
  - name: Install and configure OVN
    shell: bash
    run: |
      sudo apt-get update -y
      sudo apt-get install ovn-host ovn-central -y
      sudo ovs-vsctl set open_vswitch .                            \
           external_ids:ovn-remote=unix:/var/run/ovn/ovnsb_db.sock \
           external_ids:ovn-encap-type=geneve                      \
           external_ids:ovn-encap-ip=127.0.0.1
  - name: Free up runner disk space
    uses: ./.github/actions/free-disk-space
  - name: Set AppArmor mode to complain
    shell: bash
    run: |
      sudo apt-get update -y
      sudo apt install apparmor-utils -y
      sudo aa-complain /etc/apparmor.d/* 
