{{- if and (.Values.global.pixee.ai.openai.enabled) (.Values.global.pixee.ai.openai.key) (not .Values.global.pixee.ai.openai.existingSecret)}}
---
apiVersion: v1
kind: Secret
metadata:
  name: openai-secrets
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
type: Opaque
data:
  {{ .Values.global.pixee.ai.openai.secretKeys.apiKey }}: {{ .Values.global.pixee.ai.openai.key | b64enc }}
{{- end }}

{{- if and (.Values.global.pixee.ai.azure.enabled) (.Values.global.pixee.ai.azure.key) (not .Values.global.pixee.ai.azure.existingSecret)}}
---
apiVersion: v1
kind: Secret
metadata:
  name: azure-openai-secrets
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
type: Opaque
data:
  {{ .Values.global.pixee.ai.azure.secretKeys.apiKey }}: {{ .Values.global.pixee.ai.azure.key | b64enc }}
{{- end }}


{{ if hasKey ((.Values.global).replicated) "dockerconfigjson" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: image-pull-secret
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.global.replicated.dockerconfigjson }}
{{ end }}

{{ if not .Values.global.pixee.authentication.oidc.client.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: oidc-client-secrets
type: Opaque
data:
  {{ .Values.global.pixee.authentication.oidc.client.secretKeys.secretKey }}: {{ .Values.global.pixee.authentication.oidc.client.secret | default "" | b64enc }}
{{- end }}

{{ if and .Values.global.pixee.authentication.restApi.apiKey .Values.global.pixee.authentication.enabled (not .Values.global.pixee.authentication.restApi.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: rest-api-auth-key
type: Opaque
data:
  {{ .Values.global.pixee.authentication.restApi.secretKeys.apiKey }}: {{ .Values.global.pixee.authentication.restApi.apiKey | b64enc }}
{{ end }}