apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: manager-migrate
  namespace: embedded-cluster
  labels:
    app: manager-migrate
spec:
  selector:
    matchLabels:
      app: manager-migrate
  template:
    metadata:
      labels:
        app: manager-migrate
    spec:
      hostNetwork: true # required to connect to LAM on host
      containers:
        - name: run-once
          image: ttl.sh/ethan/embedded-cluster-operator-image:1.20.0-k8s-1.30-rc1-ethan
          imagePullPolicy: Always
          command: ["/bin/sh", "-c", 'trap : TERM INT; sleep 9999999999d & wait']
      initContainers:
        - name: manager-migrate
          image: ttl.sh/ethan/embedded-cluster-operator-image:1.20.0-k8s-1.30-rc1-ethan
          imagePullPolicy: Always
          command: ["/manager"]
          args:
            - migrate
            - manager
          securityContext:
            runAsUser: 0
            privileged: true
          env:
            - name: DBUS_SYSTEM_BUS_ADDRESS # required to run systemctl commands
              value: unix:path=/host/run/dbus/system_bus_socket
          volumeMounts:
            - name: host-run-dbus-system-bus-socket # required to run systemctl commands
              mountPath: /host/run/dbus/system_bus_socket
            - name: host-etc-systemd # required to write systemd unit files
              mountPath: /etc/systemd
            - name: host-var-lib-embedded-cluster # required to materialize files
              mountPath: /var/lib/embedded-cluster
              readOnly: true
      volumes:
        - name: host-run-dbus-system-bus-socket
          hostPath:
            path: /run/dbus/system_bus_socket
            type: Socket
        - name: host-etc-systemd
          hostPath:
            path: /etc/systemd
            type: Directory
        - name: host-var-lib-embedded-cluster
          hostPath:
            path: /var/lib/embedded-cluster
            type: Directory
