name: Free Disk Space
description: Free up Github runner disk space

runs:
  using: composite
  steps:
  - name: Free disk space
    shell: bash
    run: |
      df -h

      # these take a long time to run (sometimes over 10 minutes) but we need disk space...
      sudo docker system prune -af
      sudo rm -rf /usr/local/lib/android

      sudo rm -rf \
        /opt/hostedtoolcache/CodeQL \
        /opt/hostedtoolcache/Python \
        /opt/hostedtoolcache/PyPy \
        /opt/microsoft/powershell \
        /opt/ghc \
        /opt/az

      sudo rm -rf \
        /usr/share/swift \
        /usr/share/dotnet \
        /usr/lib/jvm \
        /usr/local/share/boost \
        /usr/local/lib/heroku \
        /usr/local/julia* \
        /usr/local/.ghcup \
        /usr/local/share/powershell \
        /usr/local/bin/aliyun \
        /usr/local/bin/azcopy \
        /usr/local/bin/bicep \
        /usr/local/bin/cpack \
        /usr/local/bin/hub \
        /usr/local/bin/minikube \
        /usr/local/bin/packer \
        /usr/local/bin/pulumi* \
        /usr/local/bin/sam \
        /usr/local/bin/stack \
        /usr/local/bin/terraform \
        /usr/local/bin/oc

      df -h
