name: Free Disk Space
description: Free up Github runner disk space

runs:
  using: composite
  steps:
  - name: Free disk space
    shell: bash
    run: |
      df -h
      sudo docker system prune -af
      sudo rm -rf /usr/local/lib/android
      sudo rm -rf /opt/hostedtoolcache/CodeQL
      sudo rm -rf /opt/hostedtoolcache/Python
      sudo rm -rf /usr/share/dotnet
      sudo rm -rf /opt/ghc
      sudo rm -rf /usr/local/share/boost
      df -h
