name: Free Disk Space
description: Free up Github runner disk space

runs:
  using: composite
  steps:
  - name: Free disk space
    shell: bash
    run: |
      df -h
      echo "Starting disk space cleanup at $(date)"
      start_time=$(date +%s)
      
      echo "Removing CodeQL cache"
      sudo rm -rf /opt/hostedtoolcache/CodeQL
      echo "CodeQL cache removal completed in $(($(date +%s) - start_time)) seconds"
      df -h
      start_time=$(date +%s)
      
      echo "Removing Python cache"
      sudo rm -rf /opt/hostedtoolcache/Python
      echo "Python cache removal completed in $(($(date +%s) - start_time)) seconds"
      df -h
      start_time=$(date +%s)
      
      echo "Removing .NET shared directory"
      sudo rm -rf /usr/share/dotnet
      echo ".NET shared directory removal completed in $(($(date +%s) - start_time)) seconds"
      df -h
      start_time=$(date +%s)
      
      echo "Removing GHC"
      sudo rm -rf /opt/ghc
      echo "GHC removal completed in $(($(date +%s) - start_time)) seconds"
      df -h
      start_time=$(date +%s)

      echo "Removing PowerShell"
      sudo rm -rf /usr/local/share/powershell
      echo "PowerShell removal completed in $(($(date +%s) - start_time)) seconds"
      df -h
      start_time=$(date +%s)

      echo "Removing Swift"
      sudo rm -rf /usr/share/swift
      echo "Swift removal completed in $(($(date +%s) - start_time)) seconds"
      df -h
      start_time=$(date +%s)

      echo "Removing GHCup"
      sudo rm -rf /usr/local/.ghcup
      echo "GHCup removal completed in $(($(date +%s) - start_time)) seconds"
      df -h
      start_time=$(date +%s)

      echo "Removing JVM"
      sudo rm -rf /usr/lib/jvm
      echo "JVM removal completed in $(($(date +%s) - start_time)) seconds"
      df -h
      start_time=$(date +%s)
      
      echo "Removing Boost shared directory"
      sudo rm -rf /usr/local/share/boost
      echo "Boost shared directory removal completed in $(($(date +%s) - start_time)) seconds"
      df -h
      
      echo "Disk space cleanup finished at $(date)"
