package:
  name: iptables-wrappers
  version: 2
  epoch: 0
  description: Wrapper scripts for using iptables in containers
  copyright:
    - license: Apache-2.0

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - ip6tables
      - busybox

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kubernetes-sigs/iptables-wrappers
      tag: v${{package.version}}
      expected-commit: e139a115350974aac8a82ec4b815d2845f86997e

  - runs: |
      # This script generates a wrapper based on the version
      # of iptables provided by the build environment.
      ./iptables-wrapper-installer.sh

      mkdir -p ${{targets.contextdir}}/sbin
      mv /sbin/iptables-wrapper ${{targets.contextdir}}/sbin/iptables-wrapper

  - uses: strip
