package:
  name: openebs-provisioner-localpv
  version: ${PACKAGE_VERSION}
  epoch: 0
  description: Dynamically provision Kubernetes Local Volumes using different kinds of storage available on the Kubernetes nodes.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - busybox
      - ca-certificates-bundle
      - go
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 0672ae3a8ad5cc385ff0a3a76cfaa52f4851e641
      repository: https://github.com/openebs/dynamic-localpv-provisioner
      tag: v${{package.version}}

  - runs: |
      export RELEASE_TAG=${{package.version}}
      make provisioner-localpv
      mkdir -p ${{targets.contextdir}}/usr/bin
      cp bin/provisioner-localpv/provisioner-localpv ${{targets.contextdir}}/usr/bin/

  - uses: strip

update:
  enabled: true
  manual: true
  github:
    identifier: openebs/dynamic-localpv-provisioner
    strip-prefix: v

test:
  pipeline:
    - runs: |
        provisioner-localpv --help 2>&1 | grep 'Usage'
