apiVersion: velero.io/v1
kind: Backup
metadata:
  name: backup
  annotations:
    preserve: me
spec:
  ttl: 36h0m0s
  includedNamespaces:
  - my-app
  hooks:
    resources:
    - name: test-hook
      includedResources:
      - 'pods'
      labelSelector:
        matchLabels:
          app: example
          component: nginx
      pre:
      - exec:
          container: nginx
          command:
          - /bin/uname
          - -a
      post:
      - exec:
          command:
           - /bin/uname
           - -a
