apiVersion: velero.io/v1
kind: Restore
metadata:
  name: restore
  annotations:
    preserve: me
spec:
  backupName: backup
  hooks:
    resources:
    - name: restore-hook-1
      includedNamespaces:
      - my-app
      postHooks:
      - init:
          initContainers:
          - name: restore-hook-init1
            image: proxy.replicated.com/anonymous/nginx:1.24-alpine
            command:
            - echo -n "FOOBARBAZ" >> /tmp/foobarbaz
