apiVersion: kots.io/v1beta1
kind: Config
spec:
  groups:
    - name: config_group
      title: The First Config Group
      items:
        - name: hostname
          title: Hostname
          type: text
        - name: pw
          title: Password
          type: password
        - name: auth_type
          title: Authentication Method
          type: radio
          default: "basic"
          items:
            - name: basic
              title: Basic Authentication
            - name: oauth
              title: OAuth Authentication
            - name: ldap
              title: LDAP Authentication
        - name: configuration_notes
          title: Configuration Notes
          type: textarea
          placeholder: "Enter any additional configuration notes or comments here..."
        - name: welcome_info
          title: |
            ## Welcome to the Configuration

            Please review the following **important information** before proceeding with your embedded cluster smoke test staging application setup:

            - Ensure all required fields are completed accurately to avoid configuration errors during deployment
            - Test connectivity after configuration changes to verify that all network settings are properly configured
            - Refer to the [comprehensive documentation](https://docs.example.com) for detailed explanations of each configuration option
            - Review security best practices outlined in the [security guide](https://docs.example.com/security) before finalizing your setup
            - Consider backup and disaster recovery options as described in the [operational guide](https://docs.example.com/operations)

            ### Authentication Configuration

            When configuring authentication methods, please note that different authentication types have specific requirements:

            1. **Basic Authentication**: Uses simple username/password combinations stored locally
            2. **OAuth Authentication**: Requires external OAuth provider configuration and proper callback URLs
            3. **LDAP Authentication**: Needs connection details to your LDAP server including bind credentials and search parameters

            ### Network Configuration

            Ensure that your network configuration allows for proper communication between all cluster components. This includes verifying that firewall rules permit traffic on the necessary ports and that DNS resolution is working correctly for all internal and external services.

            > **Important**: Changes to authentication settings will require a complete restart of the application. Please ensure you have scheduled appropriate maintenance windows for these changes.

            > **Warning**: Incorrect network configuration can result in cluster instability or complete service outages. Always test configuration changes in a staging environment first.
          type: label
