{{- if .Values.client.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nginx-app.fullname" . }}-client
  labels:
    {{- include "nginx-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: client
spec:
  replicas: {{ .Values.client.replicaCount }}
  selector:
    matchLabels:
      {{- include "nginx-app.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: client
  template:
    metadata:
      labels:
        {{- include "nginx-app.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: client
    spec:
      {{- if .Values.client.imagePullSecrets }}
      imagePullSecrets:
        {{- if .Values.client.imagePullSecrets }}
        {{- toYaml .Values.client.imagePullSecrets | nindent 8 }}
        {{- end }}
      {{- end }}
      serviceAccountName: {{ include "nginx-app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}-client
        image: "{{ .Values.client.image.repository }}:{{ .Values.client.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.client.image.pullPolicy }}
        env:
        - name: SERVER_HOST
          value: {{ include "nginx-app.fullname" . }}
        - name: SERVER_SERVICE_PORT
          value: "{{ .Values.server.service.port }}"
        - name: INTERVAL_SECONDS
          value: "{{ .Values.client.intervalSeconds }}"
        command:
          - "/bin/sh"
          - "-c"
          - |
            while true; do
              echo "$(date) - Making request to http://${SERVER_HOST}:${SERVER_SERVICE_PORT}/"
              curl -s http://${SERVER_HOST}:${SERVER_SERVICE_PORT}/
              echo ""
              echo "Sleeping for ${INTERVAL_SECONDS} seconds..."
              sleep ${INTERVAL_SECONDS}
            done
        resources:
          {{- toYaml .Values.client.resources | nindent 10 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }} 