apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx-app.fullname" . }}-config
  labels:
    {{- include "nginx-app.labels" . | nindent 4 }}
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Welcome to Nginx</title>
    </head>
    <body>
      <h1>Welcome to Nginx!</h1>
      <p>This is a test page served by Nginx.</p>
    </body>
    </html> 