apiVersion: velero.io/v1
kind: Restore
metadata:
  name: restore
  annotations:
    preserve: me
spec:
  backupName: backup
  includedNamespaces:
  - my-app
  hooks:
    resources:
    - name: restore-hook-1
      includedNamespaces:
      - app
      postHooks:
      - init:
          initContainers:
          - name: restore-hook-init1
            image: proxy.replicated.com/anonymous/nginx:1.24-alpine
            command:
            - /bin/ash
            - -c
            - echo -n "FOOBARBAZ" > /tmp/foobarbaz
