apiVersion: kots.io/v1beta1
kind: HelmChart
metadata:
  name: redis-app
spec:
  chart:
    name: redis-app
    chartVersion: 0.1.0
  namespace: redis-app
  useHelmInstall: true
  values:
    server:
      replicaCount: 3
      image:
        repository: redis
        tag: "7.2"
      service:
        type: ClusterIP
        port: 6379
    client:
      enabled: true
      replicaCount: 3
      image:
        repository: redis
        tag: "7.2"
      intervalSeconds: 5
