apiVersion: velero.io/v1
kind: Restore
metadata:
  name: restore
  annotations:
    preserve: me
spec:
  backupName: backup
  includedNamespaces:
  - '*'
  hooks:
    resources:
    - name: restore-hook-1
      includedNamespaces:
      - kotsadm
      labelSelector:
        matchLabels:
          app: example
      postHooks:
      - init:
          initContainers:
          - name: restore-hook-init1
            image: 'repl{{ LocalImageName "nginx:1.25-alpine" }}'
            command:
            - /bin/ash
            - -c
            - echo -n "FOOBARBAZ" > /tmp/foobarbaz
