apiVersion: embeddedcluster.replicated.com/v1beta1
kind: Config
metadata:
  name: "testconfig"
spec:
  version: "dev-metadata"
  roles:
    controller:
      labels:
        controller-label: controller-label-value
      name: controller-test
    custom:
      - labels:
          abc-test-label: abc-test-label-value
          abc-test-label-two: abc-test-label-value-2
        name: abc
      - labels:
          xyz-test-label: xyz-value
        name: xyz
      - labels:
          final-test-label: final-value
        name: final
  unsupportedOverrides:
    k0s: |
      config:
        metadata:
          name: foo
        spec:
          telemetry:
            enabled: false
          api:
            extraArgs:
              service-node-port-range: 80-32767
  extensions:
    helm:
      repositories:
        - name: ingress-nginx
          url: https://kubernetes.github.io/ingress-nginx
      charts:
        - name: ingress-nginx
          chartname: ingress-nginx/ingress-nginx
          namespace: ingress-nginx
          version: "4.8.3"
          order: 2
          values: |
            controller:
              service:
                type: NodePort
                nodePorts:
                  http: "80"
                  https: "443"
