{{- if .Values.global.pixee.tls }}
{{- if eq (dig "type" "" .Values.global.pixee.tls) "request" }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: {{ .Values.global.replicated.customerEmail }}
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt
    # Enable the HTTP-01 challenge provider
    solvers:
      - http01:
          ingress:
            ingressClassName: "nginx"
{{- end }}
{{- if eq (dig "type" "" .Values.global.pixee.tls) "generate" }}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
{{- end }}
{{- end }}