name: 'Build and push a dep image with apko'
description: 'Composite action for building and pushing a dep image with apko'
inputs:
  apko-config:
    description: 'Path to apko config'
    required: true

  image-name:
    description: 'Full destination image name'
    required: true

  registry-username:
    description: 'Username to login to registry'
    default: ''
    required: false

  registry-password:
    description: 'Password to login to registry'
    default: ''
    required: false

runs:
  using: "composite"
  steps:
    - uses: chainguard-images/actions/apko-publish@main
      with:
        config: ${{ inputs.apko-config }}
        archs: amd64
        tag: ${{ inputs.image-name }}
        vcs-url: true
        generic-user: ${{ inputs.registry-username }}
        generic-pass: ${{ inputs.registry-password }}
