# source: https://github.com/chainguard-images/images/blob/4317e36114e989a8dcf744c4685cd60eb8582447/images/calico/configs/latest.node.apko.yaml
contents:
  repositories:
    - https://packages.wolfi.dev/os
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
  packages:
    - busybox
    - calico-node=${PACKAGE_VERSION}

accounts:
  groups:
    - groupname: nonroot
      gid: 65532
  users:
    - username: nonroot
      uid: 65532
      gid: 65532
  # calico-node is responsible for many host level networking tasks and as such, needs root
  run-as: 0

environment:
  # Tell sv where to find the services
  SVDIR: /etc/service/enabled

paths:
  - path: /etc/service/available
    type: directory
    uid: 0
    gid: 0
    permissions: 0o755
  - path: /etc/calico
    type: directory
    uid: 65532
    gid: 65532
    permissions: 0o755

entrypoint:
  command: /usr/sbin/start_runit
