apiVersion: apps/v1
kind: Deployment
metadata:
  name: second
  labels:
    app: second
    replicated.com/disaster-recovery: app
spec:
  replicas: 0
  selector:
    matchLabels:
      app: second
  template:
    metadata:
      labels:
        app: second
    spec:
      containers:
        - name: nginx
          image: us-east4-docker.pkg.dev/replicated-qa/ec-smoke-test/nginx:1.24-alpine
          resources:
            limits:
              memory: '32Mi'
              cpu: '50m'
