apiVersion: kots.io/v1beta2
kind: HelmChart
metadata:
  name: nginx-app
spec:
  chart:
    name: nginx-app
    chartVersion: 0.1.0
  namespace: nginx-app
  values:
    server:
      image:
        # TODO: revert repo to "ec-e2e-proxy.testcluster.net" once EC 2.2.0 is released
        # as custom domains have been disabled on the channel and enabled in the EC config
        # but domains in the EC config are only supported in EC 2.2.0 and above
        repository: repl{{ HasLocalRegistry | ternary LocalRegistryHost "registry.staging.replicated.com" }}/repl{{ HasLocalRegistry | ternary LocalRegistryNamespace "proxy/embedded-cluster-smoke-test-staging-app/us-east4-docker.pkg.dev/replicated-qa/ec-smoke-test" }}/nginx
      service:
        type: ClusterIP
        port: 80
      replicaCount: 1
      imagePullSecrets:
        - name: '{{repl ImagePullSecretName }}'
    client:
      enabled: true
      image:
        # TODO: revert repo to "ec-e2e-proxy.testcluster.net" once EC 2.2.0 is released
        # as custom domains have been disabled on the channel and enabled in the EC config
        # but domains in the EC config are only supported in EC 2.2.0 and above
        repository: repl{{ HasLocalRegistry | ternary LocalRegistryHost "registry.staging.replicated.com" }}/repl{{ HasLocalRegistry | ternary LocalRegistryNamespace "proxy/embedded-cluster-smoke-test-staging-app/us-east4-docker.pkg.dev/replicated-qa/ec-smoke-test" }}/curl
      replicaCount: 1
      intervalSeconds: 60
      imagePullSecrets:
        - name: '{{repl ImagePullSecretName }}'
    replicated:
      enabled: true
      image:
        # TODO: revert repo to "ec-e2e-proxy.testcluster.net" once EC 2.2.0 is released
        # as custom domains have been disabled on the channel and enabled in the EC config
        # but domains in the EC config are only supported in EC 2.2.0 and above
        registry: repl{{ HasLocalRegistry | ternary LocalRegistryHost "registry.staging.replicated.com" }}
        repository: repl{{ HasLocalRegistry | ternary LocalRegistryNamespace "proxy/embedded-cluster-smoke-test-staging-app/replicated" }}/replicated-sdk
      imagePullSecrets:
        - name: '{{repl ImagePullSecretName }}'
  builder:
    replicated:
      enabled: true
