apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dr-fixture-data
  labels:
    app: example
    component: nginx
    replicated.com/disaster-recovery: app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
