apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "test-app.fullname" . }}-config
  labels:
    {{- include "test-app.labels" . | nindent 4 }}
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Welcome to Test App!</title>
      <style>
        body {
          width: 35em;
          margin: 0 auto;
          font-family: Tahoma, Verdana, Arial, sans-serif;
        }
      </style>
    </head>
    <body>
      <h1>Welcome to Test App!</h1>
      <p>If you see this page, the nginx web server is successfully installed and
      working.</p>
      <p>This is a sample application deployed via Helm.</p>
    </body>
    </html> 