name: End to End

inputs:
  test-env:
    description: 'onpr or onmerge'
    required: true

runs:
  using: "composite"
  strategy:
    fail-fast: false
    matrix:
      tests:
      - TestSingleNodeInstallation
      - TestSingleNodeInstallationRockyLinux8
      - TestSingleNodeInstallationDebian12
      - TestSingleNodeInstallationCentos8Stream
      - TestVersion
      - TestMultiNodeInteractiveInstallation
      - TestInstallWithDisabledAddons
      - TestHostPreflight
      - TestUnsupportedOverrides
      - TestMultiNodeInstallation
      - TestMultiNodeReset
  steps:
  - name: Move Docker aside
    run: |
      sudo systemctl stop docker
      sudo iptables -F
      sudo iptables -P FORWARD ACCEPT
  - name: Install and Configure LXD
    run: |
      sudo lxd init --auto
      sudo snap set lxd daemon.group=adm
      sudo snap restart lxd
      sudo lxd waitready
  - name: Install and configure OVN
    run: |
      sudo apt-get update -y
      sudo apt-get install ovn-host ovn-central -y
      sudo ovs-vsctl set open_vswitch .                            \
           external_ids:ovn-remote=unix:/var/run/ovn/ovnsb_db.sock \
           external_ids:ovn-encap-type=geneve                      \
           external_ids:ovn-encap-ip=127.0.0.1
  - name: Setup Go
    uses: actions/setup-go@v5
    with:
      go-version: "1.21.0"
  - name: Free up runner disk space
    run: |
      sudo rm -rf /usr/local/lib/android
      sudo rm -rf /opt/hostedtoolcache/CodeQL
      sudo rm -rf /opt/hostedtoolcache/Python
  - name: E2E
    run: |
      make e2e-test-onpr TEST_NAME=${{ matrix.tests }}
