name: Cleanup Resources

on:
  schedule:
    # Run every 3 hours
    - cron: '0 */3 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  archive-instances:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up environment
        run: |
          # Set default values for the script
          echo "DRY_RUN=false" >> $GITHUB_ENV

      - name: Run archive instances script
        env:
          REPLICATED_APP: "embedded-cluster-smoke-test-staging-app"
          REPLICATED_API_TOKEN: ${{ secrets.STAGING_REPLICATED_API_TOKEN }}
          REPLICATED_API_ORIGIN: "https://api.staging.replicated.com"
          COUNT: ${{ env.COUNT }}
          DRY_RUN: ${{ env.DRY_RUN }}
        run: |
          # Make script executable and run it
          chmod +x ./scripts/archive-instances.sh
          ./scripts/archive-instances.sh

  demote-channel-releases:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up environment
        run: |
          # Set default values for the script
          echo "DRY_RUN=false" >> $GITHUB_ENV
          echo "START_PAGE=1" >> $GITHUB_ENV
          echo "PAGE_SIZE=100" >> $GITHUB_ENV

      - name: Run demote channel releases script
        env:
          REPLICATED_APP: "embedded-cluster-smoke-test-staging-app"
          REPLICATED_API_TOKEN: ${{ secrets.STAGING_REPLICATED_API_TOKEN }}
          REPLICATED_API_ORIGIN: "https://api.staging.replicated.com"
          DRY_RUN: ${{ env.DRY_RUN }}
          START_PAGE: ${{ env.START_PAGE }}
          PAGE_SIZE: ${{ env.PAGE_SIZE }}
        run: |
          # Make script executable and run it
          chmod +x ./scripts/demote-channel-releases.sh
          ./scripts/demote-channel-releases.sh
