[build]
  publish = "dist"
  command = "npm run build"
  base = "/web"

[context.dev]
  base = "/"

[functions]
  node_bundler = "esbuild"
  included_files = ["../api/docs/swagger.yaml"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
