[context.production]
  publish = "dist"
  command = "npm run build"
  base = "/web"

[context.deploy-preview]
  publish = "dist"
  command = "npm run build"
  base = "/web"

[contetxt.dev]
  base = "/"
  publish = "dist"

[functions]
  node_bundler = "esbuild"
  included_files = ["../api/docs/**"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
